import { NavigationTree } from "@/@types/navigation";
import { baseNavigationObj } from "../baseNavigation";

const ROOT_COMPONENTS = "/components";

const path = (root: string, item: string) => `${root}${item}`;

export const components: NavigationTree = {
  ...baseNavigationObj["components"],
  type: "root",
  childs: [
    {
      id: "components.basic-ui",
      type: "collapse",
      path: path(ROOT_COMPONENTS, "/basic-ui"),
      title: "Basic UI",
      transKey: "nav.components.basic-ui.basic-ui",
      icon: "components.basic-ui",
      childs: [
        {
          id: "components.basic-ui.avatar",
          type: "item",
          path: path(ROOT_COMPONENTS, "/basic-ui/avatar"),
          title: "Avatar",
          transKey: "nav.components.basic-ui.avatar",
        },
        {
          id: "components.basic-ui.button",
          type: "item",
          path: path(ROOT_COMPONENTS, "/basic-ui/button"),
          title: "Button",
          transKey: "nav.components.basic-ui.button",
        },
        {
          id: "components.basic-ui.badge",
          type: "item",
          path: path(ROOT_COMPONENTS, "/basic-ui/badge"),
          title: "Badge",
          transKey: "nav.components.basic-ui.badge",
        },
        {
          id: "components.basic-ui.tag",
          type: "item",
          path: path(ROOT_COMPONENTS, "/basic-ui/tag"),
          title: "Tag",
          transKey: "nav.components.basic-ui.tag",
        },
        {
          id: "components.basic-ui.divider",
          type: "item",
          path: path(ROOT_COMPONENTS, "/basic-ui/divider"),
          title: "Divider",
          transKey: "nav.components.basic-ui.divider",
        },
        {
          id: "components.basic-ui.typography",
          type: "item",
          path: path(ROOT_COMPONENTS, "/basic-ui/typography"),
          title: "Typography",
          transKey: "nav.components.basic-ui.typography",
        },
      ],
    },
    {
      id: "components.data-display",
      type: "collapse",
      path: path(ROOT_COMPONENTS, "/data-display"),
      title: "Data Display",
      transKey: "nav.components.data-display.data-display",
      icon: "components.data-display",
      childs: [
        {
          id: "components.data-display.box",
          type: "item",
          path: path(ROOT_COMPONENTS, "/data-display/box"),
          title: "Box",
          transKey: "nav.components.data-display.box",
        },
        {
          id: "components.data-display.popover",
          type: "item",
          path: path(ROOT_COMPONENTS, "/data-display/popover"),
          title: "Popover",
          transKey: "nav.components.data-display.popover",
        },
        {
          id: "components.data-display.timeline",
          type: "item",
          path: path(ROOT_COMPONENTS, "/data-display/timeline"),
          title: "Timeline",
          transKey: "nav.components.data-display.timeline",
        },
        {
          id: "components.data-display.collapse",
          type: "item",
          path: path(ROOT_COMPONENTS, "/data-display/collapse"),
          title: "Collapse",
          transKey: "nav.components.data-display.collapse",
        },
        {
          id: "components.data-display.legend",
          type: "item",
          path: path(ROOT_COMPONENTS, "/data-display/legend"),
          title: "Legend",
          transKey: "nav.components.data-display.legend",
        },
        {
          id: "components.data-display.mask",
          type: "item",
          path: path(ROOT_COMPONENTS, "/data-display/mask"),
          title: "Mask",
          transKey: "nav.components.data-display.mask",
        },
        {
          id: "components.data-display.contextual-help",
          type: "item",
          path: path(ROOT_COMPONENTS, "/data-display/contextual-help"),
          title: "Contextual Help",
          transKey: "nav.components.data-display.contextual-help",
        },
      ],
    },
    {
      id: "components.navigation",
      type: "collapse",
      path: path(ROOT_COMPONENTS, "/navigation"),
      title: "Navigation",
      transKey: "nav.components.navigation.navigation",
      icon: "components.navigation",
      childs: [
        {
          id: "components.navigation.accordion",
          type: "item",
          path: path(ROOT_COMPONENTS, "/navigation/accordion"),
          title: "Accordion",
          transKey: "nav.components.navigation.accordion",
        },
        {
          id: "components.navigation.tab",
          type: "item",
          path: path(ROOT_COMPONENTS, "/navigation/tab"),
          title: "Tab",
          transKey: "nav.components.navigation.tab",
        },
        {
          id: "components.navigation.dropdown",
          type: "item",
          path: path(ROOT_COMPONENTS, "/navigation/dropdown"),
          title: "Dropdown",
          transKey: "nav.components.navigation.dropdown",
        },
        {
          id: "components.navigation.steps",
          type: "item",
          path: path(ROOT_COMPONENTS, "/navigation/steps"),
          title: "Steps",
          transKey: "nav.components.navigation.steps",
        },
        {
          id: "components.navigation.pagination",
          type: "item",
          path: path(ROOT_COMPONENTS, "/navigation/pagination"),
          title: "Pagination",
          transKey: "nav.components.navigation.pagination",
        },
        {
          id: "components.navigation.menu-list",
          type: "item",
          path: path(ROOT_COMPONENTS, "/navigation/menu-list"),
          title: "Menu List",
          transKey: "nav.components.navigation.menu-list",
        },
        {
          id: "components.navigation.treeview",
          type: "item",
          path: path(ROOT_COMPONENTS, "/navigation/treeview"),
          title: "Treeview",
          transKey: "nav.components.navigation.treeview",
        },
      ],
    },
    {
      id: "components.loading",
      type: "collapse",
      path: path(ROOT_COMPONENTS, "/loading"),
      title: "Loading",
      transKey: "nav.components.loading.loading",
      icon: "components.loading",
      childs: [
        {
          id: "components.loading.progress",
          type: "item",
          path: path(ROOT_COMPONENTS, "/loading/progress"),
          title: "Progress",
          transKey: "nav.components.loading.progress",
        },
        {
          id: "components.loading.circlebar",
          type: "item",
          path: path(ROOT_COMPONENTS, "/loading/circlebar"),
          title: "Circlebar",
          transKey: "nav.components.loading.circlebar",
        },
        {
          id: "components.loading.skeleton",
          type: "item",
          path: path(ROOT_COMPONENTS, "/loading/skeleton"),
          title: "Skeleton",
          transKey: "nav.components.loading.skeleton",
        },
        {
          id: "components.loading.spinner",
          type: "item",
          path: path(ROOT_COMPONENTS, "/loading/spinner"),
          title: "Spinner",
          transKey: "nav.components.loading.spinner",
        },
      ],
    },
    {
      id: "components.feedback",
      type: "collapse",
      path: path(ROOT_COMPONENTS, "/feedback"),
      title: "Feedback",
      transKey: "nav.components.feedback.feedback",
      icon: "components.feedback",
      childs: [
        {
          id: "components.feedback.tooltip",
          type: "item",
          path: path(ROOT_COMPONENTS, "/feedback/tooltip"),
          title: "Tooltip",
          transKey: "nav.components.feedback.tooltip",
        },
        {
          id: "components.feedback.notification",
          type: "item",
          path: path(ROOT_COMPONENTS, "/feedback/notification"),
          title: "Notification",
          transKey: "nav.components.feedback.notification",
        },
        {
          id: "components.feedback.alert",
          type: "item",
          path: path(ROOT_COMPONENTS, "/feedback/alert"),
          title: "Alert",
          transKey: "nav.components.feedback.alert",
        },
      ],
    },
    {
      id: "components.modal",
      type: "collapse",
      path: path(ROOT_COMPONENTS, "/modal"),
      title: "Modal",
      transKey: "nav.components.modal.modal",
      icon: "components.modal",
      childs: [
        {
          id: "components.modal.modal",
          type: "item",
          path: path(ROOT_COMPONENTS, "/modal/modal"),
          title: "Modal",
          transKey: "nav.components.modal.modal",
        },
        {
          id: "components.modal.drawer",
          type: "item",
          path: path(ROOT_COMPONENTS, "/modal/drawer"),
          title: "Drawer",
          transKey: "nav.components.modal.drawer",
        },
      ],
    },
    {
      id: "components.advanced",
      type: "collapse",
      path: path(ROOT_COMPONENTS, "/advanced"),
      title: "Advanced",
      transKey: "nav.components.advanced.advanced",
      icon: "components.advanced",
      childs: [
        {
          id: "components.scroll-shadow",
          type: "item",
          path: path(ROOT_COMPONENTS, "/advanced/scroll-shadow"),
          title: "Scroll Shadow",
          transKey: "nav.components.advanced.scroll-shadow",
        },
        {
          id: "components.charts",
          type: "item",
          path: path(ROOT_COMPONENTS, "/advanced/charts"),
          title: "Charts",
          transKey: "nav.components.advanced.charts",
        },
        {
          id: "components.carousel",
          type: "item",
          path: path(ROOT_COMPONENTS, "/advanced/carousel"),
          title: "Carousel",
          transKey: "nav.components.advanced.carousel",
        },
      ],
    },
  ],
};
