import { baseNavigationObj } from "../baseNavigation";
import { NavigationTree } from "@/@types/navigation";

const ROOT_DASHBOARDS = "/dashboards";

const path = (root: string, item: string) => `${root}${item}`;

export const dashboards: NavigationTree = {
  ...baseNavigationObj["dashboards"],
  type: "root",
  childs: [
    {
      id: "dashboards.sales",
      path: path(ROOT_DASHBOARDS, "/sales"),
      type: "item",
      title: "Sales",
      transKey: "nav.dashboards.sales",
      icon: "dashboards.sales",
    },
    {
      id: "dashboards.crm-analytics",
      path: path(ROOT_DASHBOARDS, "/crm-analytics"),
      type: "item",
      title: "CRM Analytics",
      transKey: "nav.dashboards.crm-analytics",
      icon: "dashboards.crm-analytics",
    },
    {
      id: "dashboards.orders",
      path: path(ROOT_DASHBOARDS, "/orders"),
      type: "item",
      title: "Orders",
      transKey: "nav.dashboards.orders",
      icon: "dashboards.orders",
    },
    {
      id: "dashboards.divide-1",
      type: "divider",
    },
    {
      id: "dashboards.crypto",
      path: path(ROOT_DASHBOARDS, "/crypto"),
      type: "collapse",
      title: "Cryptocurrency",
      transKey: "nav.dashboards.crypto",
      icon: "dashboards.crypto",
      childs: [
        {
          id: "dashboards.crypto-1",
          type: "item",
          path: path(ROOT_DASHBOARDS, "/crypto/crypto-1"),
          title: "Cryptocurrency v1",
          transKey: "nav.dashboards.crypto-1",
        },
        {
          id: "dashboards.crypto-2",
          type: "item",
          path: path(ROOT_DASHBOARDS, "/crypto/crypto-2"),
          title: "Cryptocurrency v2",
          transKey: "nav.dashboards.crypto-2",
        },
      ],
    },
    {
      id: "dashboards.banking",
      path: path(ROOT_DASHBOARDS, "/banking"),
      type: "collapse",
      title: "Cryptocurrency",
      transKey: "nav.dashboards.banking",
      icon: "dashboards.banking",
      childs: [
        {
          id: "dashboards.banking-1",
          type: "item",
          path: path(ROOT_DASHBOARDS, "/banking/banking-1"),
          title: "Banking v1",
          transKey: "nav.dashboards.banking-1",
        },
        {
          id: "dashboards.banking-2",
          type: "item",
          path: path(ROOT_DASHBOARDS, "/banking/banking-2"),
          title: "Banking v2",
          transKey: "nav.dashboards.banking-2",
        },
      ],
    },
    {
      id: "dashboards.personal",
      path: path(ROOT_DASHBOARDS, "/personal"),
      type: "item",
      title: "Personal",
      transKey: "nav.dashboards.personal",
      icon: "dashboards.personal",
    },
    {
      id: "dashboards.cms-analytics",
      path: path(ROOT_DASHBOARDS, "/cms-analytics"),
      type: "item",
      title: "CMS Analytics",
      transKey: "nav.dashboards.cms-analytics",
      icon: "dashboards.cms-analytics",
    },
    {
      id: "dashboards.influencer",
      path: path(ROOT_DASHBOARDS, "/influencer"),
      type: "item",
      title: "Influencer",
      transKey: "nav.dashboards.influencer",
      icon: "dashboards.influencer",
    },
    {
      id: "dashboards.travel",
      path: path(ROOT_DASHBOARDS, "/travel"),
      type: "item",
      title: "Travel",
      transKey: "nav.dashboards.travel",
      icon: "dashboards.travel",
    },
    {
      id: "dashboards.teacher",
      path: path(ROOT_DASHBOARDS, "/teacher"),
      type: "item",
      title: "Teacher",
      transKey: "nav.dashboards.teacher",
      icon: "dashboards.teacher",
    },
    {
      id: "dashboards.education",
      path: path(ROOT_DASHBOARDS, "/education"),
      type: "item",
      title: "Education",
      transKey: "nav.dashboards.education",
      icon: "dashboards.education",
    },
    {
      id: "dashboards.authors",
      path: path(ROOT_DASHBOARDS, "/authors"),
      type: "item",
      title: "Authors",
      transKey: "nav.dashboards.authors",
      icon: "dashboards.authors",
    },
    {
      id: "dashboards.doctor",
      path: path(ROOT_DASHBOARDS, "/doctor"),
      type: "item",
      title: "Doctor",
      transKey: "nav.dashboards.doctor",
      icon: "dashboards.doctor",
    },
    {
      id: "dashboards.employees",
      path: path(ROOT_DASHBOARDS, "/employees"),
      type: "item",
      title: "Employees",
      transKey: "nav.dashboards.employees",
      icon: "dashboards.employees",
    },
    {
      id: "dashboards.workspaces",
      path: path(ROOT_DASHBOARDS, "/workspaces"),
      type: "item",
      title: "Workspaces",
      transKey: "nav.dashboards.workspaces",
      icon: "dashboards.workspaces",
    },
    {
      id: "dashboards.meetings",
      path: path(ROOT_DASHBOARDS, "/meetings"),
      type: "item",
      title: "Meetings",
      transKey: "nav.dashboards.meetings",
      icon: "dashboards.meetings",
    },
    {
      id: "dashboards.projects-board",
      path: path(ROOT_DASHBOARDS, "/projects-board"),
      type: "item",
      title: "Projects Board",
      transKey: "nav.dashboards.projects-board",
      icon: "dashboards.projects-board",
    },
    {
      id: "dashboards.divide-2",
      type: "divider",
    },
    {
      id: "dashboards.widget-ui",
      path: path(ROOT_DASHBOARDS, "/widget-ui"),
      type: "item",
      title: "Widgets UI",
      transKey: "nav.dashboards.widget-ui",
      icon: "dashboards.widget",
    },
    {
      id: "dashboards.widget-contact",
      path: path(ROOT_DASHBOARDS, "/widget-contact"),
      type: "item",
      title: "Widgets Contact",
      transKey: "nav.dashboards.widget-contact",
      icon: "dashboards.widget",
    },
  ],
};
