import { baseNavigationObj } from "../baseNavigation";
import { NavigationTree } from "@/@types/navigation";

const ROOT_FORMS = "/forms";

const path = (root: string, item: string) => `${root}${item}`;

export const forms: NavigationTree = {
  ...baseNavigationObj["forms"],
  type: "root",
  childs: [
    {
      id: "forms.ekyc-form",
      type: "item",
      path: path(ROOT_FORMS, "/ekyc-form"),
      title: "eKYC Form",
      transKey: "nav.forms.ekyc-form",
      icon: "forms.ekyc-form",
    },
    {
      id: "forms.add-product-form",
      type: "item",
      path: path(ROOT_FORMS, "/add-product-form"),
      title: "Add Product Form",
      transKey: "nav.forms.add-product-form",
      icon: "forms.add-product-form",
    },
    {
      id: "forms.new-post-form",
      type: "item",
      path: path(ROOT_FORMS, "/new-post-form"),
      title: "New Post Form",
      transKey: "nav.forms.new-post-form",
      icon: "forms.new-post-form",
    },
    {
      id: "pages.divide-2",
      type: "divider",
    },
    {
      id: "forms.input",
      type: "item",
      path: path(ROOT_FORMS, "/input"),
      title: "Form Input",
      transKey: "nav.forms.input",
      icon: "forms.input",
    },
    {
      id: "forms.input-group",
      type: "item",
      path: path(ROOT_FORMS, "/input-group"),
      title: "Input Group",
      transKey: "nav.forms.input-group",
      icon: "forms.input-group",
    },
    {
      id: "forms.input-mask",
      type: "item",
      path: path(ROOT_FORMS, "/input-mask"),
      title: "Input Mask",
      transKey: "nav.forms.input-mask",
      icon: "forms.input-mask",
    },
    {
      id: "forms.checkbox",
      type: "item",
      path: path(ROOT_FORMS, "/checkbox"),
      title: "Checkbox",
      transKey: "nav.forms.checkbox",
      icon: "forms.checkbox",
    },
    {
      id: "forms.radio",
      type: "item",
      path: path(ROOT_FORMS, "/radio"),
      title: "Radio",
      transKey: "nav.forms.radio",
      icon: "forms.radio",
    },
    {
      id: "forms.switch",
      type: "item",
      path: path(ROOT_FORMS, "/switch"),
      title: "Switch",
      transKey: "nav.forms.switch",
      icon: "forms.switch",
    },
    {
      id: "forms.swap",
      type: "item",
      path: path(ROOT_FORMS, "/swap"),
      title: "Swap",
      transKey: "nav.forms.swap",
      icon: "forms.swap",
    },
    {
      id: "forms.textarea",
      type: "item",
      path: path(ROOT_FORMS, "/textarea"),
      title: "Textarea",
      transKey: "nav.forms.textarea",
      icon: "forms.textarea",
    },
    {
      id: "forms.select",
      type: "item",
      path: path(ROOT_FORMS, "/select"),
      title: "Select",
      transKey: "nav.forms.select",
      icon: "forms.select",
    },
    {
      id: "forms.range",
      type: "item",
      path: path(ROOT_FORMS, "/range"),
      title: "Range",
      transKey: "nav.forms.range",
      icon: "forms.range",
    },
    {
      id: "forms.listbox",
      type: "item",
      path: path(ROOT_FORMS, "/listbox"),
      title: "Listbox",
      transKey: "nav.forms.listbox",
      icon: "forms.listbox",
    },
    {
      id: "forms.autocomplete",
      type: "item",
      path: path(ROOT_FORMS, "/autocomplete"),
      title: "Autocomplete",
      transKey: "nav.forms.autocomplete",
      icon: "forms.autocomplete",
    },
    {
      id: "forms.file-upload",
      type: "item",
      path: path(ROOT_FORMS, "/file-upload"),
      title: "File Upload",
      transKey: "nav.forms.file-upload",
      icon: "forms.file-upload",
    },
    {
      id: "forms.form-validation",
      type: "item",
      path: path(ROOT_FORMS, "/form-validation"),
      title: "Form Validation",
      transKey: "nav.forms.form-validation",
      icon: "forms.form-validation",
    },
    {
      id: "forms.text-editor",
      type: "item",
      path: path(ROOT_FORMS, "/text-editor"),
      title: "text-editor",
      transKey: "nav.forms.text-editor",
      icon: "forms.text-editor",
    },
    {
      id: "forms.filepond",
      type: "item",
      path: path(ROOT_FORMS, "/filepond"),
      title: "Filepond",
      transKey: "nav.forms.filepond",
      icon: "forms.filepond",
    },
    {
      id: "forms.datepicker",
      type: "item",
      path: path(ROOT_FORMS, "/datepicker"),
      title: "Datepicker",
      transKey: "nav.forms.datepicker",
      icon: "forms.datepicker",
    },
  ],
};
