import { NavigationTree } from "@/@types/navigation";

const ROOT_PROTOTYPES = "/prototypes";

const path = (root: string, item: string) => `${root}${item}`;

export const prototypes: NavigationTree = {
  id: "prototypes",
  type: "root",
  path: "prototypes",
  title: "Prototypes",
  transKey: "nav.prototypes.prototypes",
  icon: "prototypes",
  childs: [
    {
      id: "prototypes.onboarding",
      path: path(ROOT_PROTOTYPES, "/onboarding"),
      type: "collapse",
      title: "Onboarding",
      transKey: "nav.prototypes.onboarding",
      icon: "prototypes.onboarding",
      childs: [
        {
          id: "prototypes.onboarding-1",
          type: "item",
          path: path(ROOT_PROTOTYPES, "/onboarding/onboarding-1"),
          title: "Onboarding 1",
          transKey: "nav.prototypes.onboarding-1",
          icon: "prototypes",
        },
        {
          id: "prototypes.onboarding-2",
          type: "item",
          path: path(ROOT_PROTOTYPES, "/onboarding/onboarding-2"),
          title: "Onboarding 2",
          transKey: "nav.prototypes.onboarding-2",
          icon: "prototypes",
        },
      ],
    },
    {
      id: "prototypes.users-card",
      path: path(ROOT_PROTOTYPES, "/users-card"),
      type: "collapse",
      title: "Users List",
      transKey: "nav.prototypes.users-card",
      icon: "prototypes.users-card",
      childs: [
        {
          id: "prototypes.users-card-1",
          type: "item",
          path: path(ROOT_PROTOTYPES, "/users-card/users-card-1"),
          title: "Users List 1",
          transKey: "nav.prototypes.users-card-1",
        },
        {
          id: "prototypes.users-card-2",
          type: "item",
          path: path(ROOT_PROTOTYPES, "/users-card/users-card-2"),
          title: "Users List 2",
          transKey: "nav.prototypes.users-card-2",
        },
        {
          id: "prototypes.users-card-3",
          type: "item",
          path: path(ROOT_PROTOTYPES, "/users-card/users-card-3"),
          title: "Users List 3",
          transKey: "nav.prototypes.users-card-3",
        },
        {
          id: "prototypes.users-card-4",
          type: "item",
          path: path(ROOT_PROTOTYPES, "/users-card/users-card-4"),
          title: "Users List 4",
          transKey: "nav.prototypes.users-card-4",
        },
        {
          id: "prototypes.users-card-5",
          type: "item",
          path: path(ROOT_PROTOTYPES, "/users-card/users-card-5"),
          title: "Users List 5",
          transKey: "nav.prototypes.users-card-5",
        },
        {
          id: "prototypes.users-card-6",
          type: "item",
          path: path(ROOT_PROTOTYPES, "/users-card/users-card-6"),
          title: "Users List 6",
          transKey: "nav.prototypes.users-card-6",
        },
        {
          id: "prototypes.users-card-7",
          type: "item",
          path: path(ROOT_PROTOTYPES, "/users-card/users-card-7"),
          title: "Users List 7",
          transKey: "nav.prototypes.users-card-7",
        },
      ],
    },
    {
      id: "prototypes.blog-card",
      path: path(ROOT_PROTOTYPES, "/blog-card"),
      type: "collapse",
      title: "Blog List",
      transKey: "nav.prototypes.blog-card",
      icon: "prototypes.blog-card",
      childs: [
        {
          id: "prototypes.blog-card-1",
          type: "item",
          path: path(ROOT_PROTOTYPES, "/blog-card/blog-card-1"),
          title: "Blog List 1",
          transKey: "nav.prototypes.blog-card-1",
        },
        {
          id: "prototypes.blog-card-2",
          type: "item",
          path: path(ROOT_PROTOTYPES, "/blog-card/blog-card-2"),
          title: "Blog List 2",
          transKey: "nav.prototypes.blog-card-2",
        },
        {
          id: "prototypes.blog-card-3",
          type: "item",
          path: path(ROOT_PROTOTYPES, "/blog-card/blog-card-3"),
          title: "Blog List 3",
          transKey: "nav.prototypes.blog-card-3",
        },
        {
          id: "prototypes.blog-card-4",
          type: "item",
          path: path(ROOT_PROTOTYPES, "/blog-card/blog-card-4"),
          title: "Blog List 4",
          transKey: "nav.prototypes.blog-card-4",
        },
        {
          id: "prototypes.blog-card-5",
          type: "item",
          path: path(ROOT_PROTOTYPES, "/blog-card/blog-card-5"),
          title: "Blog List 5",
          transKey: "nav.prototypes.blog-card-5",
        },
        {
          id: "prototypes.blog-card-6",
          type: "item",
          path: path(ROOT_PROTOTYPES, "/blog-card/blog-card-6"),
          title: "Blog List 6",
          transKey: "nav.prototypes.blog-card-6",
        },
        {
          id: "prototypes.blog-card-7",
          type: "item",
          path: path(ROOT_PROTOTYPES, "/blog-card/blog-card-7"),
          title: "Blog List 7",
          transKey: "nav.prototypes.blog-card-7",
        },
        {
          id: "prototypes.blog-card-8",
          type: "item",
          path: path(ROOT_PROTOTYPES, "/blog-card/blog-card-8"),
          title: "Blog List 8",
          transKey: "nav.prototypes.blog-card-8",
        },
      ],
    },
    {
      id: "prototypes.post-details",
      path: path(ROOT_PROTOTYPES, "/post-details"),
      type: "item",
      title: "Post Details",
      transKey: "nav.prototypes.post-details",
      icon: "prototypes.post-details",
    },
    {
      id: "prototypes.price-list",
      path: path(ROOT_PROTOTYPES, "/price-list"),
      type: "collapse",
      title: "Price List",
      transKey: "nav.prototypes.price-list",
      icon: "prototypes.price-list",
      childs: [
        {
          id: "prototypes.price-list-1",
          type: "item",
          path: path(ROOT_PROTOTYPES, "/price-list/price-list-1"),
          title: "Price List 1",
          transKey: "nav.prototypes.price-list-1",
        },
        {
          id: "prototypes.price-list-2",
          type: "item",
          path: path(ROOT_PROTOTYPES, "/price-list/price-list-2"),
          title: "Price List 2",
          transKey: "nav.prototypes.price-list-2",
        },
        {
          id: "prototypes.price-list-3",
          type: "item",
          path: path(ROOT_PROTOTYPES, "/price-list/price-list-3"),
          title: "Price List 3",
          transKey: "nav.prototypes.price-list-3",
        },
        {
          id: "prototypes.price-list-4",
          type: "item",
          path: path(ROOT_PROTOTYPES, "/price-list/price-list-4"),
          title: "Price List 4",
          transKey: "nav.prototypes.price-list-4",
        },
      ],
    },
    {
      id: "prototypes.help",
      path: path(ROOT_PROTOTYPES, "/help"),
      type: "collapse",
      title: "Help",
      transKey: "nav.prototypes.help",
      icon: "prototypes.help",
      childs: [
        {
          id: "prototypes.help-1",
          type: "item",
          path: path(ROOT_PROTOTYPES, "/help/help-1"),
          title: "Help 1",
          transKey: "nav.prototypes.help-1",
        },
        {
          id: "prototypes.help-2",
          type: "item",
          path: path(ROOT_PROTOTYPES, "/help/help-2"),
          title: "Help 2",
          transKey: "nav.prototypes.help-2",
        },
        {
          id: "prototypes.help-3",
          type: "item",
          path: path(ROOT_PROTOTYPES, "/help/help-3"),
          title: "Help 3",
          transKey: "nav.prototypes.help-3",
        },
      ],
    },
    {
      id: "prototypes.invoice",
      path: path(ROOT_PROTOTYPES, "/invoice"),
      type: "collapse",
      title: "Invoice",
      transKey: "nav.prototypes.invoice",
      icon: "prototypes.invoice",
      childs: [
        {
          id: "prototypes.invoice-1",
          type: "item",
          path: path(ROOT_PROTOTYPES, "/invoice/invoice-1"),
          title: "Invoice 1",
          transKey: "nav.prototypes.invoice-1",
        },
        {
          id: "prototypes.invoice-2",
          type: "item",
          path: path(ROOT_PROTOTYPES, "/invoice/invoice-2"),
          title: "Invoice 2",
          transKey: "nav.prototypes.invoice-2",
        },
      ],
    },
    {
      id: "prototypes.divide-1",
      type: "divider",
    },
    {
      id: "prototypes.sign-in",
      path: path(ROOT_PROTOTYPES, "/sign-in"),
      type: "collapse",
      title: "Sign In",
      transKey: "nav.prototypes.sign-in",
      icon: "prototypes.sign-in",
      childs: [
        {
          id: "prototypes.sign-in-1",
          type: "item",
          path: path(ROOT_PROTOTYPES, "/sign-in/sign-in-1"),
          title: "Sign In 1",
          transKey: "nav.prototypes.sign-in-1",
        },
        {
          id: "prototypes.sign-in-2",
          type: "item",
          path: path(ROOT_PROTOTYPES, "/sign-in/sign-in-2"),
          title: "Sign In 2",
          transKey: "nav.prototypes.sign-in-2",
        },
      ],
    },
    {
      id: "prototypes.sign-up",
      path: path(ROOT_PROTOTYPES, "/sign-up"),
      type: "collapse",
      title: "Sign Up",
      transKey: "nav.prototypes.sign-up",
      icon: "prototypes.sign-up",
      childs: [
        {
          id: "prototypes.sign-up-1",
          type: "item",
          path: path(ROOT_PROTOTYPES, "/sign-up/sign-up-1"),
          title: "Sign Up 1",
          transKey: "nav.prototypes.sign-up-1",
        },
        {
          id: "prototypes.sign-up-2",
          type: "item",
          path: path(ROOT_PROTOTYPES, "/sign-up/sign-up-2"),
          title: "Sign Up 2",
          transKey: "nav.prototypes.sign-up-2",
        },
      ],
    },
    {
      id: "prototypes.divide-2",
      type: "divider",
    },
    {
      id: "prototypes.errors",
      path: path(ROOT_PROTOTYPES, "/errors"),
      type: "collapse",
      title: "Error Pages",
      transKey: "nav.prototypes.errors",
      icon: "prototypes.errors",
      childs: [
        {
          id: "prototypes.error-404-1",
          type: "item",
          path: path(ROOT_PROTOTYPES, "/errors/404-v1"),
          title: "Error 404 v1",
          transKey: "nav.prototypes.error-404-1",
        },
        {
          id: "prototypes.error-404-2",
          type: "item",
          path: path(ROOT_PROTOTYPES, "/errors/404-v2"),
          title: "Error 404 v2",
          transKey: "nav.prototypes.error-404-2",
        },
        {
          id: "prototypes.error-404-3",
          type: "item",
          path: path(ROOT_PROTOTYPES, "/errors/404-v3"),
          title: "Error 404 v3",
          transKey: "nav.prototypes.error-404-3",
        },
        {
          id: "prototypes.error-404-4",
          type: "item",
          path: path(ROOT_PROTOTYPES, "/errors/404-v4"),
          title: "Error 404 v4",
          transKey: "nav.prototypes.error-404-4",
        },
        {
          id: "prototypes.error-401",
          type: "item",
          path: path(ROOT_PROTOTYPES, "/errors/401"),
          title: "Error 401",
          transKey: "nav.prototypes.error-401",
        },
        {
          id: "prototypes.error-429",
          type: "item",
          path: path(ROOT_PROTOTYPES, "/errors/429"),
          title: "Error 429",
          transKey: "nav.prototypes.error-429",
        },
        {
          id: "prototypes.error-500",
          type: "item",
          path: path(ROOT_PROTOTYPES, "/errors/500"),
          title: "Error 500",
          transKey: "nav.prototypes.error-500",
        },
      ],
    },
  ],
};
