export interface Project {
  project_id: number;
  partner_image: string;
  partner_name: string;
  project_name: string;
  project_desc: string;
  tags: string[];
  collaborators: {
    name: string;
    image?: string | null;
  }[];
  progress: number;
  started_at: string;
  deadline: string;
}

export const projectsList: Project[] = [
    {
        project_id: 1,
        partner_image: "/images/logos/google.svg",
        partner_name: "Samsung",
        project_name: "CodeX",
        project_desc: "A platform for collaborative coding and debugging",
        tags: ["virtual reality", "robotics"],
        collaborators: [
            { name: "Edsel Dewen", image: "/images/avatar/avatar-8.jpg" },
        ],
        progress: 19,
        started_at: "8/10/2022",
        deadline: "8/10/2023",
    },
    {
        project_id: 2,
        partner_image: "/images/logos/microsoft.svg",
        partner_name: "HP",
        project_name: "DataViz",
        project_desc:
            "A tool for creating interactive data visualizations and dashboards",
        tags: ["IT education", "augmented reality", "artificial intelligence"],
        collaborators: [
            { name: "Howard Messer", image: "/images/avatar/avatar-15.jpg" },
            { name: "Alissa Shallcross", image: "/images/avatar/avatar-3.jpg" },
            { name: "Marika Cutts", image: "/images/avatar/avatar-10.jpg" },
        ],
        progress: 64,
        started_at: "11/13/2022",
        deadline: "12/13/2022",
    },
    {
        project_id: 3,
        partner_image: "/images/logos/behance-round.svg",
        partner_name: "Sony",
        project_name: "SmartHome",
        project_desc:
            "A system for controlling and monitoring smart devices in your home",
        tags: ["Web development", "virtual reality", "data science"],
        collaborators: [
            { name: "Francis Laible", image: "/images/avatar/avatar-19.jpg" },
            { name: "Dannye Bowser", image: "/images/avatar/avatar-14.jpg" },
            { name: "Abey Axup", image: "/images/avatar/avatar-20.jpg" },
        ],
        progress: 12,
        started_at: "3/25/2023",
        deadline: "2/25/2024",
    },
    {
        project_id: 4,
        partner_image: "/images/logos/flickr-round.svg",
        partner_name: "Lenovo",
        project_name: "CyberSec",
        project_desc:
            "A system for controlling and monitoring smart devices in your home",
        tags: ["blockchain", "robotics"],
        collaborators: [{ name: "Marilin Kynett", image: undefined }],
        progress: 0,
        started_at: "1/7/2023",
        deadline: "9/7/2023",
    },
    {
        project_id: 5,
        partner_image: "/images/logos/microsoft.svg",
        partner_name: "Huawei",
        project_name: "ChatBot",
        project_desc: "A chatbot that can answer questions and provide assistance",
        tags: ["IT consulting", "internet of things"],
        collaborators: [
            { name: "Haskell Tooth", image: "/images/avatar/avatar-15.jpg" },
            { name: "Georgianna Teck", image: undefined },
        ],
        progress: 86,
        started_at: "11/19/2022",
        deadline: "10/19/2023",
    },
    {
        project_id: 6,
        partner_image: "/images/logos/microsoft.svg",
        partner_name: "Apple",
        project_name: "AIr",
        project_desc:
            "An artificial intelligence system that can recognize and respond to voice commands",
        tags: ["user interface design"],
        collaborators: [
            { name: "Lynnett O'Sheerin", image: "/images/avatar/avatar-16.jpg" },
            { name: "Vlad Matyatin", image: "/images/avatar/avatar-15.jpg" },
            { name: "Farra Deddum", image: "/images/avatar/avatar-18.jpg" },
            { name: "Ingrid Convery", image: "/images/avatar/avatar-1.jpg" },
            { name: "Dunc Franklyn", image: undefined },
        ],
        progress: 100,
        started_at: "6/11/2022",
        deadline: "8/11/2022",
    },
    {
        project_id: 7,
        partner_image: "/images/logos/pinterest-round.svg",
        partner_name: "Acer",
        project_name: "WebDev",
        project_desc:
            "A website builder that lets you create and host your own websites",
        tags: ["automation", "internet of things"],
        collaborators: [
            { name: "Suzanne Bootman", image: "/images/avatar/avatar-1.jpg" },
            { name: "Jacky Hamilton", image: "/images/avatar/avatar-8.jpg" },
            { name: "Joseph Wehner", image: "/images/avatar/avatar-17.jpg" },
            { name: "Drona Dregan", image: "/images/avatar/avatar-1.jpg" },
        ],
        progress: 61,
        started_at: "5/19/2022",
        deadline: "5/19/2023",
    },
    {
        project_id: 8,
        partner_image: "/images/logos/microsoft.svg",
        partner_name: "Huawei",
        project_name: "Cloudy",
        project_desc:
            "A cloud computing service that offers storage & computing and networking resources",
        tags: ["machine learning", "automation"],
        collaborators: [
            { name: "Edgard Connick", image: "/images/avatar/avatar-13.jpg" },
            { name: "Antony Domnin", image: "/images/avatar/avatar-20.jpg" },
            { name: "Godard Bernuzzi", image: "/images/avatar/avatar-15.jpg" },
            { name: "Derrek Gravestone", image: "/images/avatar/avatar-17.jpg" },
            { name: "Stavros Treadwell", image: "/images/avatar/avatar-3.jpg" },
        ],
        progress: 77,
        started_at: "8/13/2022",
        deadline: "12/13/2022",
    },
    {
        project_id: 9,
        partner_image: "/images/logos/microsoft.svg",
        partner_name: "Sony",
        project_name: "VRy",
        project_desc:
            "A virtual reality app that lets you explore and create immersive environments",
        tags: ["automation", "gaming", "data science"],
        collaborators: [
            { name: "Rosamond Mueller", image: "/images/avatar/avatar-14.jpg" },
            { name: "Ned McGrane", image: "/images/avatar/avatar-3.jpg" },
            { name: "Joyous Brigdale", image: "/images/avatar/avatar-12.jpg" },
        ],
        progress: 8,
        started_at: "12/3/2022",
        deadline: "6/3/2023",
    },
    {
        project_id: 10,
        partner_image: "/images/logos/adobe_portfolio-round.svg",
        partner_name: "Sony",
        project_name: "IoTize",
        project_desc: "A device that connects any object to the internet of things",
        tags: ["system administration"],
        collaborators: [
            { name: "Shaina Scriver", image: "/images/avatar/avatar-16.jpg" },
            { name: "Teddy Walcar", image: "/images/avatar/avatar-5.jpg" },
        ],
        progress: 77,
        started_at: "9/3/2022",
        deadline: "7/3/2023",
    },
    {
        project_id: 11,
        partner_image: "/images/logos/flickr-round.svg",
        partner_name: "HP",
        project_name: "BioTech",
        project_desc:
            "A biotechnology project that uses living organisms or their components for various purposes",
        tags: ["Web development", "system administration"],
        collaborators: [
            { name: "Murial Donn", image: undefined },
            { name: "Farrah Giamitti", image: "/images/avatar/avatar-11.jpg" },
            { name: "Alice Disley", image: "/images/avatar/avatar-17.jpg" },
            { name: "Jennee Yurenin", image: undefined },
            { name: "Lindsay Dellatorre", image: undefined },
        ],
        progress: 14,
        started_at: "10/14/2022",
        deadline: "7/14/2023",
    },
    {
        project_id: 12,
        partner_image: "/images/logos/behance-round.svg",
        partner_name: "Dell",
        project_name: "GameOn",
        project_desc:
            "A game development studio that creates and publishes video games",
        tags: ["Web development"],
        collaborators: [
            { name: "Chrissie Dashwood", image: "/images/avatar/avatar-16.jpg" },
            { name: "Akim Perroni", image: "/images/avatar/avatar-9.jpg" },
            { name: "Sullivan Splain", image: "/images/avatar/avatar-2.jpg" },
            { name: "Bevon Kirimaa", image: "/images/avatar/avatar-2.jpg" },
        ],
        progress: 5,
        started_at: "8/5/2022",
        deadline: "6/5/2023",
    },
    {
        project_id: 13,
        partner_image: "/images/logos/google.svg",
        partner_name: "HP",
        project_name: "EduTech",
        project_desc:
            "An educational technology project that enhances learning and teaching",
        tags: ["IT education", "mobile app development"],
        collaborators: [
            { name: "Kriste Hutchcraft", image: undefined },
            { name: "Jacklin Ruddy", image: "/images/avatar/avatar-18.jpg" },
            { name: "Derrek Manson", image: "/images/avatar/avatar-19.jpg" },
            { name: "Teresina Gockeler", image: "/images/avatar/avatar-3.jpg" },
        ],
        progress: 58,
        started_at: "10/8/2022",
        deadline: "3/8/2023",
    },
    {
        project_id: 14,
        partner_image: "/images/logos/adobe_portfolio-round.svg",
        partner_name: "LG",
        project_name: "FinTech",
        project_desc:
            "A financial technology project that provides innovative solutions for banking and finance",
        tags: ["Web development"],
        collaborators: [{ name: "Horten Chainey", image: undefined }],
        progress: 20,
        started_at: "12/17/2022",
        deadline: "9/17/2023",
    },
    {
        project_id: 15,
        partner_image: "/images/logos/flickr-round.svg",
        partner_name: "Lenovo",
        project_name: "HealthIT",
        project_desc:
            "A health information technology project that improves health care delivery and outcomes",
        tags: ["cybersecurity", "blockchain", "artificial intelligence"],
        collaborators: [
            { name: "Rorie Merriton", image: "/images/avatar/avatar-15.jpg" },
            { name: "Adham Triggol", image: undefined },
            { name: "Marcille Beardsley", image: "/images/avatar/avatar-16.jpg" },
            { name: "Talia Skunes", image: "/images/avatar/avatar-12.jpg" },
            { name: "Serge Prichet", image: "/images/avatar/avatar-9.jpg" },
        ],
        progress: 54,
        started_at: "1/15/2023",
        deadline: "9/15/2023",
    },
    {
        project_id: 16,
        partner_image: "/images/logos/behance-round.svg",
        partner_name: "Microsoft",
        project_name: "GreenIT",
        project_desc:
            "A cryptocurrency project that uses blockchain technology for secure transactions",
        tags: ["blockchain", "artificial intelligence", "user interface design"],
        collaborators: [
            { name: "Aylmar Broadway", image: undefined },
            { name: "Carly Breffit", image: undefined },
            { name: "Coraline Gennrich", image: "/images/avatar/avatar-1.jpg" },
            { name: "June Pawsey", image: undefined },
        ],
        progress: 2,
        started_at: "5/13/2022",
        deadline: "2/13/2023",
    },
    {
        project_id: 17,
        partner_image: "/images/logos/google.svg",
        partner_name: "Samsung",
        project_name: "SocialNet",
        project_desc:
            "An environmental technology project that promotes sustainability and reduces environmental impact",
        tags: ["graphic design"],
        collaborators: [
            { name: "Myer Hakey", image: "/images/avatar/avatar-20.jpg" },
        ],
        progress: 90,
        started_at: "5/27/2022",
        deadline: "5/27/2023",
    },
    {
        project_id: 18,
        partner_image: "/images/logos/pinterest-round.svg",
        partner_name: "Huawei",
        project_name: "Ecom",
        project_desc:
            "A social networking project that connects people and communities",
        tags: ["e-commerce"],
        collaborators: [
            { name: "Lyle Canter", image: "/images/avatar/avatar-7.jpg" },
            { name: "Nannie Masi", image: "/images/avatar/avatar-16.jpg" },
        ],
        progress: 37,
        started_at: "8/21/2022",
        deadline: "10/21/2022",
    },
    {
        project_id: 19,
        partner_image: "/images/logos/google.svg",
        partner_name: "Huawei",
        project_name: "MediaLab",
        project_desc:
            "An e-commerce project that sells products or services online",
        tags: ["machine learning", "user interface design"],
        collaborators: [
            { name: "Delphine Napolione", image: "/images/avatar/avatar-2.jpg" },
            { name: "Melesa Cutridge", image: "/images/avatar/avatar-17.jpg" },
        ],
        progress: 50,
        started_at: "6/27/2022",
        deadline: "6/27/2023",
    },
    {
        project_id: 20,
        partner_image: "/images/logos/adobe_portfolio-round.svg",
        partner_name: "Apple",
        project_name: "CodeX",
        project_desc:
            "A media production project that creates and distributes digital content",
        tags: ["cybersecurity", "user experience design", "technical support"],
        collaborators: [
            { name: "Elise Westwater", image: undefined },
            { name: "Magdalena Krzyzowski", image: undefined },
            { name: "Karole McGreary", image: "/images/avatar/avatar-18.jpg" },
        ],
        progress: 48,
        started_at: "10/2/2022",
        deadline: "12/2/2022",
    },
    {
        project_id: 21,
        partner_image: "/images/logos/pinterest-round.svg",
        partner_name: "HP",
        project_name: "DataViz",
        project_desc: "A platform for collaborative coding and debugging",
        tags: ["cybersecurity", "digital marketing", "blockchain"],
        collaborators: [
            { name: "Berky Ebenezer", image: "/images/avatar/avatar-7.jpg" },
            { name: "Drusi McCaughen", image: undefined },
            { name: "Wolfy Llewellin", image: "/images/avatar/avatar-1.jpg" },
            { name: "Star McGillivrie", image: "/images/avatar/avatar-15.jpg" },
        ],
        progress: 89,
        started_at: "1/5/2023",
        deadline: "1/5/2024",
    },
    {
        project_id: 22,
        partner_image: "/images/logos/behance-round.svg",
        partner_name: "Acer",
        project_name: "SmartHome",
        project_desc:
            "A tool for creating interactive data visualizations and dashboards",
        tags: ["social media", "IT audit", "cybersecurity"],
        collaborators: [
            { name: "Beth Wavell", image: undefined },
            { name: "Elroy Rhodus", image: "/images/avatar/avatar-9.jpg" },
        ],
        progress: 63,
        started_at: "8/23/2022",
        deadline: "5/23/2023",
    },
    {
        project_id: 23,
        partner_image: "/images/logos/flickr-round.svg",
        partner_name: "Razer",
        project_name: "CyberSec",
        project_desc:
            "A system for controlling and monitoring smart devices in your home",
        tags: ["IT governance and IT strategy.", "data science"],
        collaborators: [{ name: "Lorene Fattorini", image: undefined }],
        progress: 94,
        started_at: "10/26/2022",
        deadline: "5/26/2023",
    },
    {
        project_id: 24,
        partner_image: "/images/logos/pinterest-round.svg",
        partner_name: "Nintendo",
        project_name: "ChatBot",
        project_desc:
            "A system for controlling and monitoring smart devices in your home",
        tags: ["data science", "cloud computing", "virtual reality"],
        collaborators: [
            { name: "Philippe Naismith", image: "/images/avatar/avatar-8.jpg" },
            { name: "Rudolfo Petrowsky", image: undefined },
        ],
        progress: 86,
        started_at: "8/31/2022",
        deadline: "11/30/2022",
    },
    {
        project_id: 25,
        partner_image: "/images/logos/google.svg",
        partner_name: "Apple",
        project_name: "AIr",
        project_desc: "A chatbot that can answer questions and provide assistance",
        tags: ["software engineering", "internet of things", "automation"],
        collaborators: [
            { name: "Kirk de Courcy", image: "/images/avatar/avatar-3.jpg" },
            { name: "Athene Longland", image: undefined },
            { name: "Dodi Darbyshire", image: "/images/avatar/avatar-9.jpg" },
            { name: "Giff Whistlecraft", image: "/images/avatar/avatar-6.jpg" },
            { name: "Diann Quenby", image: undefined },
        ],
        progress: 34,
        started_at: "9/22/2022",
        deadline: "6/22/2023",
    },
    {
        project_id: 26,
        partner_image: "/images/logos/google.svg",
        partner_name: "Acer",
        project_name: "WebDev",
        project_desc:
            "An artificial intelligence system that can recognize and respond to voice commands",
        tags: ["cybersecurity", "system administration", "cloud computing"],
        collaborators: [
            { name: "Harper Cullagh", image: "/images/avatar/avatar-1.jpg" },
        ],
        progress: 33,
        started_at: "6/22/2022",
        deadline: "5/22/2023",
    },
    {
        project_id: 27,
        partner_image: "/images/logos/pinterest-round.svg",
        partner_name: "Microsoft",
        project_name: "Cloudy",
        project_desc:
            "A website builder that lets you create and host your own websites",
        tags: ["IT research", "virtual reality"],
        collaborators: [
            { name: "Elka Royse", image: "/images/avatar/avatar-3.jpg" },
        ],
        progress: 62,
        started_at: "7/16/2022",
        deadline: "12/16/2022",
    },
    {
        project_id: 28,
        partner_image: "/images/logos/google.svg",
        partner_name: "HP",
        project_name: "VRy",
        project_desc:
            "A cloud computing service that offers storage & computing and networking resources",
        tags: ["machine learning", "virtual reality", "automation"],
        collaborators: [
            { name: "Lizbeth Shatford", image: "/images/avatar/avatar-5.jpg" },
        ],
        progress: 15,
        started_at: "10/1/2022",
        deadline: "12/1/2022",
    },
    {
        project_id: 29,
        partner_image: "/images/logos/flickr-round.svg",
        partner_name: "Logitech",
        project_name: "IoTize",
        project_desc:
            "A virtual reality app that lets you explore and create immersive environments",
        tags: ["virtual reality"],
        collaborators: [
            { name: "Dorri Kopisch", image: "/images/avatar/avatar-4.jpg" },
            { name: "Debi Hanes", image: undefined },
            { name: "Leontine Langmead", image: "/images/avatar/avatar-16.jpg" },
            { name: "Farica Glader", image: "/images/avatar/avatar-10.jpg" },
        ],
        progress: 44,
        started_at: "6/4/2022",
        deadline: "5/4/2023",
    },
    {
        project_id: 30,
        partner_image: "/images/logos/flickr-round.svg",
        partner_name: "Microsoft",
        project_name: "BioTech",
        project_desc: "A device that connects any object to the internet of things",
        tags: [
            "IT consulting",
            "cloud computing",
            "IT governance and IT strategy.",
        ],
        collaborators: [
            { name: "Cinnamon Clawe", image: undefined },
            { name: "Karlik Bourtoumieux", image: "/images/avatar/avatar-14.jpg" },
            { name: "Coriss Cummungs", image: "/images/avatar/avatar-8.jpg" },
            { name: "Dora Kittman", image: "/images/avatar/avatar-14.jpg" },
            { name: "Faustina MacDougall", image: "/images/avatar/avatar-20.jpg" },
        ],
        progress: 77,
        started_at: "10/3/2022",
        deadline: "11/3/2022",
    },
    {
        project_id: 31,
        partner_image: "/images/logos/flickr-round.svg",
        partner_name: "Huawei",
        project_name: "GameOn",
        project_desc:
            "A biotechnology project that uses living organisms or their components for various purposes",
        tags: ["user interface design", "user experience design", "IT education"],
        collaborators: [
            { name: "Brigitte Kopf", image: undefined },
            { name: "Elroy Wallenger", image: "/images/avatar/avatar-9.jpg" },
            { name: "Yolanda Huggan", image: undefined },
        ],
        progress: 86,
        started_at: "1/7/2023",
        deadline: "7/7/2023",
    },
    {
        project_id: 32,
        partner_image: "/images/logos/adobe_portfolio-round.svg",
        partner_name: "Apple",
        project_name: "EduTech",
        project_desc:
            "A game development studio that creates and publishes video games",
        tags: ["augmented reality"],
        collaborators: [
            { name: "Evania Goldthorpe", image: undefined },
            { name: "Hussein Eickhoff", image: "/images/avatar/avatar-15.jpg" },
            { name: "Aarika McKeating", image: "/images/avatar/avatar-16.jpg" },
            { name: "Erin Golsthorp", image: "/images/avatar/avatar-12.jpg" },
        ],
        progress: 10,
        started_at: "9/3/2022",
        deadline: "9/3/2023",
    },
    {
        project_id: 33,
        partner_image: "/images/logos/adobe_portfolio-round.svg",
        partner_name: "Samsung",
        project_name: "FinTech",
        project_desc:
            "An educational technology project that enhances learning and teaching",
        tags: ["gaming", "internet of things", "mobile app development"],
        collaborators: [{ name: "Cornie Kleinberer", image: undefined }],
        progress: 9,
        started_at: "5/14/2022",
        deadline: "7/14/2022",
    },
    {
        project_id: 34,
        partner_image: "/images/logos/pinterest-round.svg",
        partner_name: "Sony",
        project_name: "HealthIT",
        project_desc:
            "A financial technology project that provides innovative solutions for banking and finance",
        tags: [
            "user interface design",
            "digital marketing",
            "system administration",
        ],
        collaborators: [
            { name: "Desmond Beverage", image: "/images/avatar/avatar-1.jpg" },
        ],
        progress: 71,
        started_at: "7/19/2022",
        deadline: "2/19/2023",
    },
    {
        project_id: 35,
        partner_image: "/images/logos/pinterest-round.svg",
        partner_name: "Acer",
        project_name: "GreenIT",
        project_desc:
            "A health information technology project that improves health care delivery and outcomes",
        tags: ["IT education", "IT consulting"],
        collaborators: [
            { name: "Spence Blackham", image: "/images/avatar/avatar-10.jpg" },
            { name: "Wilow Stringfellow", image: "/images/avatar/avatar-16.jpg" },
            { name: "Candice Alejandro", image: "/images/avatar/avatar-6.jpg" },
            { name: "Phylis Medgwick", image: undefined },
            { name: "Flory Tante", image: "/images/avatar/avatar-11.jpg" },
        ],
        progress: 8,
        started_at: "8/4/2022",
        deadline: "8/4/2023",
    },
    {
        project_id: 36,
        partner_image: "/images/logos/pinterest-round.svg",
        partner_name: "Sony",
        project_name: "SocialNet",
        project_desc:
            "A cryptocurrency project that uses blockchain technology for secure transactions",
        tags: ["mobile app development", "IT audit", "system administration"],
        collaborators: [
            { name: "Arri Matysik", image: undefined },
            { name: "Marinna Krelle", image: undefined },
            { name: "Jose Irnis", image: "/images/avatar/avatar-18.jpg" },
            { name: "Hastie Narracott", image: undefined },
            { name: "Erma Sterzaker", image: "/images/avatar/avatar-6.jpg" },
        ],
        progress: 65,
        started_at: "5/13/2022",
        deadline: "1/13/2023",
    },
    {
        project_id: 37,
        partner_image: "/images/logos/adobe_portfolio-round.svg",
        partner_name: "Sony",
        project_name: "Ecom",
        project_desc:
            "An environmental technology project that promotes sustainability and reduces environmental impact",
        tags: ["e-commerce"],
        collaborators: [
            { name: "Neron Folds", image: "/images/avatar/avatar-16.jpg" },
            { name: "Kinny Terren", image: undefined },
            { name: "Montague Karlsen", image: undefined },
        ],
        progress: 34,
        started_at: "7/17/2022",
        deadline: "5/17/2023",
    },
    {
        project_id: 38,
        partner_image: "/images/logos/adobe_portfolio-round.svg",
        partner_name: "Asus",
        project_name: "MediaLab",
        project_desc:
            "A social networking project that connects people and communities",
        tags: ["social media", "IT consulting"],
        collaborators: [
            { name: "Zaria Scolli", image: "/images/avatar/avatar-16.jpg" },
            { name: "Madelina Cawston", image: "/images/avatar/avatar-6.jpg" },
            { name: "Orlan Berrey", image: undefined },
        ],
        progress: 48,
        started_at: "1/22/2023",
        deadline: "10/22/2023",
    },
    {
        project_id: 39,
        partner_image: "/images/logos/behance-round.svg",
        partner_name: "Sony",
        project_name: "CodeX",
        project_desc:
            "An e-commerce project that sells products or services online",
        tags: ["internet of things", "blockchain", "IT consulting"],
        collaborators: [
            { name: "Esta Allardyce", image: "/images/avatar/avatar-8.jpg" },
        ],
        progress: 80,
        started_at: "12/19/2022",
        deadline: "11/19/2023",
    },
    {
        project_id: 40,
        partner_image: "/images/logos/google.svg",
        partner_name: "Razer",
        project_name: "DataViz",
        project_desc:
            "A media production project that creates and distributes digital content",
        tags: ["IT research"],
        collaborators: [
            { name: "Gordan Grellier", image: "/images/avatar/avatar-11.jpg" },
            { name: "Hedvige Gerriet", image: "/images/avatar/avatar-10.jpg" },
            { name: "Meggie Bernardt", image: undefined },
            { name: "Nara Dowsing", image: undefined },
        ],
        progress: 55,
        started_at: "11/1/2022",
        deadline: "4/1/2023",
    },
    {
        project_id: 41,
        partner_image: "/images/logos/adobe_portfolio-round.svg",
        partner_name: "LG",
        project_name: "SmartHome",
        project_desc: "A platform for collaborative coding and debugging",
        tags: ["graphic design"],
        collaborators: [
            { name: "Mathias Oke", image: "/images/avatar/avatar-12.jpg" },
        ],
        progress: 8,
        started_at: "1/22/2023",
        deadline: "6/22/2023",
    },
    {
        project_id: 42,
        partner_image: "/images/logos/flickr-round.svg",
        partner_name: "Sony",
        project_name: "CyberSec",
        project_desc:
            "A tool for creating interactive data visualizations and dashboards",
        tags: ["gaming", "Web development", "robotics"],
        collaborators: [
            { name: "Pegeen Brear", image: undefined },
            { name: "Brendon Caberas", image: "/images/avatar/avatar-15.jpg" },
        ],
        progress: 80,
        started_at: "4/2/2023",
        deadline: "3/2/2024",
    },
    {
        project_id: 43,
        partner_image: "/images/logos/adobe_portfolio-round.svg",
        partner_name: "Lenovo",
        project_name: "ChatBot",
        project_desc:
            "A system for controlling and monitoring smart devices in your home",
        tags: ["cybersecurity"],
        collaborators: [
            { name: "Jarret Revance", image: "/images/avatar/avatar-1.jpg" },
            { name: "Archy Wahlberg", image: undefined },
            { name: "Freda Spat", image: undefined },
        ],
        progress: 54,
        started_at: "4/27/2023",
        deadline: "6/27/2023",
    },
    {
        project_id: 44,
        partner_image: "/images/logos/pinterest-round.svg",
        partner_name: "Huawei",
        project_name: "AIr",
        project_desc:
            "A system for controlling and monitoring smart devices in your home",
        tags: ["user interface design"],
        collaborators: [
            { name: "Patin Godspede", image: "/images/avatar/avatar-14.jpg" },
            { name: "Howie Cable", image: undefined },
            { name: "Adler Keaveny", image: undefined },
            { name: "Sophi Frisel", image: "/images/avatar/avatar-16.jpg" },
        ],
        progress: 55,
        started_at: "1/29/2023",
        deadline: "7/29/2023",
    },
    {
        project_id: 45,
        partner_image: "/images/logos/pinterest-round.svg",
        partner_name: "Samsung",
        project_name: "WebDev",
        project_desc: "A chatbot that can answer questions and provide assistance",
        tags: ["user experience design"],
        collaborators: [
            { name: "Sibilla Weatherup", image: "/images/avatar/avatar-4.jpg" },
            { name: "Isidoro Szubert", image: "/images/avatar/avatar-11.jpg" },
            { name: "Kerrie Blanking", image: "/images/avatar/avatar-1.jpg" },
            { name: "Neddy Georgeau", image: "/images/avatar/avatar-7.jpg" },
            { name: "Pasquale Dennert", image: "/images/avatar/avatar-1.jpg" },
        ],
        progress: 85,
        started_at: "5/20/2022",
        deadline: "4/20/2023",
    },
    {
        project_id: 46,
        partner_image: "/images/logos/flickr-round.svg",
        partner_name: "Nintendo",
        project_name: "Cloudy",
        project_desc:
            "An artificial intelligence system that can recognize and respond to voice commands",
        tags: ["gaming", "IT education", "virtual reality"],
        collaborators: [
            { name: "Caresa Phython", image: "/images/avatar/avatar-6.jpg" },
            { name: "Magnum Van Zon", image: "/images/avatar/avatar-9.jpg" },
            { name: "Lacy Rugiero", image: undefined },
            { name: "Robinetta Shewsmith", image: "/images/avatar/avatar-20.jpg" },
            { name: "Norby Stogill", image: undefined },
        ],
        progress: 48,
        started_at: "2/26/2023",
        deadline: "12/26/2023",
    },
    {
        project_id: 47,
        partner_image: "/images/logos/google.svg",
        partner_name: "Apple",
        project_name: "VRy",
        project_desc:
            "A website builder that lets you create and host your own websites",
        tags: ["augmented reality"],
        collaborators: [
            { name: "Jayme Cardoso", image: "/images/avatar/avatar-9.jpg" },
            { name: "Alaster Totterdill", image: undefined },
            { name: "Rozina Creed", image: "/images/avatar/avatar-20.jpg" },
            { name: "Leela Gatchel", image: undefined },
        ],
        progress: 69,
        started_at: "8/7/2022",
        deadline: "10/7/2022",
    },
    {
        project_id: 48,
        partner_image: "/images/logos/adobe_portfolio-round.svg",
        partner_name: "Samsung",
        project_name: "IoTize",
        project_desc:
            "A cloud computing service that offers storage & computing and networking resources",
        tags: ["e-commerce"],
        collaborators: [
            { name: "Fancie Cramond", image: undefined },
            { name: "Bride St. Leger", image: undefined },
            { name: "Abra Infante", image: "/images/avatar/avatar-1.jpg" },
            { name: "Guthry Mushett", image: "/images/avatar/avatar-2.jpg" },
            { name: "Dita Simo", image: "/images/avatar/avatar-3.jpg" },
        ],
        progress: 46,
        started_at: "3/16/2023",
        deadline: "4/16/2023",
    },
    {
        project_id: 49,
        partner_image: "/images/logos/flickr-round.svg",
        partner_name: "Razer",
        project_name: "BioTech",
        project_desc:
            "A virtual reality app that lets you explore and create immersive environments",
        tags: ["IT research"],
        collaborators: [
            { name: "Curt Daffey", image: "/images/avatar/avatar-20.jpg" },
            { name: "Winston Caddell", image: undefined },
            { name: "Ebeneser Francesconi", image: undefined },
            { name: "Vern Fortey", image: "/images/avatar/avatar-8.jpg" },
            { name: "Doug Palmer", image: "/images/avatar/avatar-5.jpg" },
        ],
        progress: 8,
        started_at: "11/5/2022",
        deadline: "7/5/2023",
    },
    {
        project_id: 50,
        partner_image: "/images/logos/pinterest-round.svg",
        partner_name: "Apple",
        project_name: "GameOn",
        project_desc: "A device that connects any object to the internet of things",
        tags: ["user experience design"],
        collaborators: [
            { name: "Brenden Murphy", image: undefined },
            { name: "Darill Dudeney", image: "/images/avatar/avatar-5.jpg" },
            { name: "Pinchas Jeratt", image: undefined },
            { name: "Alleen Dyne", image: "/images/avatar/avatar-9.jpg" },
            { name: "Jenifer Gregr", image: undefined },
        ],
        progress: 56,
        started_at: "1/31/2023",
        deadline: "5/31/2023",
    },
    {
        project_id: 51,
        partner_image: "/images/logos/flickr-round.svg",
        partner_name: "Samsung",
        project_name: "EduTech",
        project_desc:
            "A biotechnology project that uses living organisms or their components for various purposes",
        tags: ["robotics", "cloud computing"],
        collaborators: [
            { name: "Brandon Manterfield", image: undefined },
            { name: "Erena Dinning", image: undefined },
        ],
        progress: 35,
        started_at: "5/15/2022",
        deadline: "5/15/2023",
    },
    {
        project_id: 52,
        partner_image: "/images/logos/behance-round.svg",
        partner_name: "Samsung",
        project_name: "FinTech",
        project_desc:
            "A game development studio that creates and publishes video games",
        tags: ["blockchain"],
        collaborators: [
            { name: "Finlay Popham", image: undefined },
            { name: "Dottie Pannaman", image: undefined },
            { name: "Warde Ivanilov", image: "/images/avatar/avatar-10.jpg" },
        ],
        progress: 74,
        started_at: "6/18/2022",
        deadline: "9/18/2022",
    },
    {
        project_id: 53,
        partner_image: "/images/logos/behance-round.svg",
        partner_name: "Razer",
        project_name: "HealthIT",
        project_desc:
            "An educational technology project that enhances learning and teaching",
        tags: ["database management"],
        collaborators: [
            { name: "Fawnia Maccaddie", image: "/images/avatar/avatar-18.jpg" },
            { name: "Riccardo Blick", image: "/images/avatar/avatar-16.jpg" },
        ],
        progress: 69,
        started_at: "8/12/2022",
        deadline: "10/12/2022",
    },
    {
        project_id: 54,
        partner_image: "/images/logos/google.svg",
        partner_name: "HP",
        project_name: "GreenIT",
        project_desc:
            "A financial technology project that provides innovative solutions for banking and finance",
        tags: ["IT research", "robotics", "mobile app development"],
        collaborators: [
            { name: "Seamus Gilstin", image: "/images/avatar/avatar-14.jpg" },
            { name: "Morgan Scripps", image: "/images/avatar/avatar-19.jpg" },
            { name: "Garald Caraher", image: "/images/avatar/avatar-6.jpg" },
            { name: "Ari Janny", image: "/images/avatar/avatar-4.jpg" },
        ],
        progress: 76,
        started_at: "12/24/2022",
        deadline: "10/24/2023",
    },
    {
        project_id: 55,
        partner_image: "/images/logos/behance-round.svg",
        partner_name: "Microsoft",
        project_name: "SocialNet",
        project_desc:
            "A health information technology project that improves health care delivery and outcomes",
        tags: ["software engineering", "automation"],
        collaborators: [
            { name: "Kristen Athy", image: "/images/avatar/avatar-16.jpg" },
            { name: "Chariot Blanque", image: undefined },
        ],
        progress: 9,
        started_at: "6/28/2022",
        deadline: "8/28/2022",
    },
    {
        project_id: 56,
        partner_image: "/images/logos/microsoft.svg",
        partner_name: "LG",
        project_name: "Ecom",
        project_desc:
            "A cryptocurrency project that uses blockchain technology for secure transactions",
        tags: ["robotics", "graphic design"],
        collaborators: [{ name: "Jolyn Osichev", image: undefined }],
        progress: 19,
        started_at: "12/9/2022",
        deadline: "3/9/2023",
    },
    {
        project_id: 57,
        partner_image: "/images/logos/flickr-round.svg",
        partner_name: "Sony",
        project_name: "MediaLab",
        project_desc:
            "An environmental technology project that promotes sustainability and reduces environmental impact",
        tags: ["automation"],
        collaborators: [
            { name: "Myrilla Skene", image: undefined },
            { name: "Kirsteni Tretwell", image: "/images/avatar/avatar-8.jpg" },
        ],
        progress: 33,
        started_at: "7/29/2022",
        deadline: "9/29/2022",
    },
    {
        project_id: 58,
        partner_image: "/images/logos/google.svg",
        partner_name: "Dell",
        project_name: "CodeX",
        project_desc:
            "A social networking project that connects people and communities",
        tags: ["IT consulting", "graphic design"],
        collaborators: [
            { name: "Rona Biggerdike", image: undefined },
            { name: "Carrie Leibold", image: undefined },
            { name: "Abra Fenge", image: "/images/avatar/avatar-9.jpg" },
            { name: "Sheff Dalyiel", image: "/images/avatar/avatar-8.jpg" },
        ],
        progress: 98,
        started_at: "4/14/2023",
        deadline: "10/14/2023",
    },
    {
        project_id: 59,
        partner_image: "/images/logos/behance-round.svg",
        partner_name: "HP",
        project_name: "DataViz",
        project_desc:
            "An e-commerce project that sells products or services online",
        tags: ["user interface design", "software engineering", "virtual reality"],
        collaborators: [
            { name: "Edee Truwert", image: "/images/avatar/avatar-7.jpg" },
            { name: "Moina Limpertz", image: "/images/avatar/avatar-20.jpg" },
            { name: "Misha Camilletti", image: "/images/avatar/avatar-16.jpg" },
        ],
        progress: 29,
        started_at: "11/29/2022",
        deadline: "10/29/2023",
    },
    {
        project_id: 60,
        partner_image: "/images/logos/google.svg",
        partner_name: "Sony",
        project_name: "SmartHome",
        project_desc:
            "A media production project that creates and distributes digital content",
        tags: ["database management", "gaming"],
        collaborators: [
            { name: "Eunice Fatkin", image: "/images/avatar/avatar-8.jpg" },
            { name: "Jeth Janes", image: "/images/avatar/avatar-16.jpg" },
            { name: "Darby Rolse", image: "/images/avatar/avatar-17.jpg" },
            { name: "Sally Addey", image: "/images/avatar/avatar-20.jpg" },
            { name: "Orlando Eldridge", image: "/images/avatar/avatar-1.jpg" },
        ],
        progress: 90,
        started_at: "2/25/2023",
        deadline: "5/25/2023",
    },
    {
        project_id: 61,
        partner_image: "/images/logos/microsoft.svg",
        partner_name: "Samsung",
        project_name: "CyberSec",
        project_desc: "A platform for collaborative coding and debugging",
        tags: ["IT governance and IT strategy."],
        collaborators: [{ name: "Jania Beccles", image: undefined }],
        progress: 48,
        started_at: "10/1/2022",
        deadline: "9/1/2023",
    },
    {
        project_id: 62,
        partner_image: "/images/logos/adobe_portfolio-round.svg",
        partner_name: "Apple",
        project_name: "ChatBot",
        project_desc:
            "A tool for creating interactive data visualizations and dashboards",
        tags: ["IT consulting", "machine learning"],
        collaborators: [
            { name: "Carrie Challen", image: "/images/avatar/avatar-6.jpg" },
            { name: "Dee Stagg", image: undefined },
        ],
        progress: 47,
        started_at: "7/16/2022",
        deadline: "11/16/2022",
    },
    {
        project_id: 63,
        partner_image: "/images/logos/flickr-round.svg",
        partner_name: "Samsung",
        project_name: "AIr",
        project_desc:
            "A system for controlling and monitoring smart devices in your home",
        tags: ["machine learning"],
        collaborators: [
            { name: "Cesya Warne", image: "/images/avatar/avatar-6.jpg" },
            { name: "Robert Heino", image: "/images/avatar/avatar-10.jpg" },
            { name: "Clemence Purslow", image: "/images/avatar/avatar-5.jpg" },
            { name: "Kimbell Vinick", image: undefined },
        ],
        progress: 41,
        started_at: "7/23/2022",
        deadline: "9/23/2022",
    },
    {
        project_id: 64,
        partner_image: "/images/logos/microsoft.svg",
        partner_name: "Sony",
        project_name: "WebDev",
        project_desc:
            "A system for controlling and monitoring smart devices in your home",
        tags: ["IT consulting", "virtual reality", "social media"],
        collaborators: [
            { name: "Ricard Goldsmith", image: undefined },
            { name: "Jerrilee Bartosek", image: "/images/avatar/avatar-8.jpg" },
        ],
        progress: 87,
        started_at: "12/11/2022",
        deadline: "9/11/2023",
    },
    {
        project_id: 65,
        partner_image: "/images/logos/behance-round.svg",
        partner_name: "Samsung",
        project_name: "Cloudy",
        project_desc: "A chatbot that can answer questions and provide assistance",
        tags: ["machine learning", "database management", "graphic design"],
        collaborators: [
            { name: "Jennee MacDermid", image: "/images/avatar/avatar-12.jpg" },
        ],
        progress: 20,
        started_at: "7/7/2022",
        deadline: "3/7/2023",
    },
    {
        project_id: 66,
        partner_image: "/images/logos/flickr-round.svg",
        partner_name: "Huawei",
        project_name: "VRy",
        project_desc:
            "An artificial intelligence system that can recognize and respond to voice commands",
        tags: ["IT education", "artificial intelligence"],
        collaborators: [
            { name: "Delmer Rubens", image: undefined },
            { name: "Armando Melbert", image: undefined },
        ],
        progress: 19,
        started_at: "6/12/2022",
        deadline: "3/12/2023",
    },
    {
        project_id: 67,
        partner_image: "/images/logos/microsoft.svg",
        partner_name: "Apple",
        project_name: "IoTize",
        project_desc:
            "A website builder that lets you create and host your own websites",
        tags: ["robotics", "digital marketing", "user experience design"],
        collaborators: [
            { name: "Monti Benning", image: undefined },
            { name: "Lane Nudds", image: undefined },
            { name: "Sabina Armitt", image: "/images/avatar/avatar-14.jpg" },
        ],
        progress: 45,
        started_at: "11/17/2022",
        deadline: "10/17/2023",
    },
    {
        project_id: 68,
        partner_image: "/images/logos/flickr-round.svg",
        partner_name: "Samsung",
        project_name: "BioTech",
        project_desc:
            "A cloud computing service that offers storage & computing and networking resources",
        tags: ["cybersecurity"],
        collaborators: [
            { name: "Rutger Dudeney", image: undefined },
            { name: "Gradey McTrustram", image: "/images/avatar/avatar-14.jpg" },
            { name: "Shina Byrde", image: "/images/avatar/avatar-7.jpg" },
            { name: "Arabel Vasenin", image: undefined },
        ],
        progress: 28,
        started_at: "7/21/2022",
        deadline: "10/21/2022",
    },
    {
        project_id: 69,
        partner_image: "/images/logos/microsoft.svg",
        partner_name: "LG",
        project_name: "GameOn",
        project_desc:
            "A virtual reality app that lets you explore and create immersive environments",
        tags: ["data science"],
        collaborators: [
            { name: "Kiel Cutten", image: "/images/avatar/avatar-20.jpg" },
        ],
        progress: 48,
        started_at: "11/18/2022",
        deadline: "9/18/2023",
    },
    {
        project_id: 70,
        partner_image: "/images/logos/pinterest-round.svg",
        partner_name: "Dell",
        project_name: "EduTech",
        project_desc: "A device that connects any object to the internet of things",
        tags: ["technical support", "machine learning", "system administration"],
        collaborators: [
            { name: "Terry Dorrity", image: "/images/avatar/avatar-12.jpg" },
            { name: "Jud Nekrews", image: "/images/avatar/avatar-12.jpg" },
            { name: "Lorilyn Dufaur", image: undefined },
            { name: "Clarie Pinchin", image: "/images/avatar/avatar-10.jpg" },
        ],
        progress: 34,
        started_at: "2/1/2023",
        deadline: "7/1/2023",
    },
    {
        project_id: 71,
        partner_image: "/images/logos/flickr-round.svg",
        partner_name: "Asus",
        project_name: "FinTech",
        project_desc:
            "A biotechnology project that uses living organisms or their components for various purposes",
        tags: ["technical support"],
        collaborators: [
            { name: "Melina Gatenby", image: "/images/avatar/avatar-8.jpg" },
            { name: "Llywellyn Tithacott", image: "/images/avatar/avatar-11.jpg" },
            { name: "Tammara Duberry", image: "/images/avatar/avatar-2.jpg" },
            { name: "Rosanne Leatherborrow", image: "/images/avatar/avatar-3.jpg" },
        ],
        progress: 29,
        started_at: "2/26/2023",
        deadline: "2/26/2024",
    },
    {
        project_id: 72,
        partner_image: "/images/logos/microsoft.svg",
        partner_name: "Lenovo",
        project_name: "HealthIT",
        project_desc:
            "A game development studio that creates and publishes video games",
        tags: ["social media", "cybersecurity", "software engineering"],
        collaborators: [
            { name: "Ken Cheese", image: "/images/avatar/avatar-15.jpg" },
        ],
        progress: 59,
        started_at: "1/7/2023",
        deadline: "7/7/2023",
    },
    {
        project_id: 73,
        partner_image: "/images/logos/flickr-round.svg",
        partner_name: "Acer",
        project_name: "GreenIT",
        project_desc:
            "An educational technology project that enhances learning and teaching",
        tags: ["user interface design"],
        collaborators: [
            { name: "Mercie Rushton", image: "/images/avatar/avatar-16.jpg" },
            { name: "Tarah Trolley", image: "/images/avatar/avatar-10.jpg" },
        ],
        progress: 60,
        started_at: "8/30/2022",
        deadline: "6/30/2023",
    },
    {
        project_id: 74,
        partner_image: "/images/logos/google.svg",
        partner_name: "Samsung",
        project_name: "SocialNet",
        project_desc:
            "A financial technology project that provides innovative solutions for banking and finance",
        tags: ["virtual reality", "system administration", "gaming"],
        collaborators: [
            { name: "Ardyth Natt", image: "/images/avatar/avatar-12.jpg" },
            { name: "Langston Batiste", image: "/images/avatar/avatar-15.jpg" },
            { name: "Bobbi Mattiuzzi", image: "/images/avatar/avatar-15.jpg" },
        ],
        progress: 50,
        started_at: "12/15/2022",
        deadline: "9/15/2023",
    },
    {
        project_id: 75,
        partner_image: "/images/logos/google.svg",
        partner_name: "Nintendo",
        project_name: "Ecom",
        project_desc:
            "A health information technology project that improves health care delivery and outcomes",
        tags: ["IT audit", "IT governance and IT strategy."],
        collaborators: [
            { name: "Blisse Gavaghan", image: "/images/avatar/avatar-15.jpg" },
        ],
        progress: 71,
        started_at: "11/23/2022",
        deadline: "6/23/2023",
    },
    {
        project_id: 76,
        partner_image: "/images/logos/microsoft.svg",
        partner_name: "Sony",
        project_name: "MediaLab",
        project_desc:
            "A cryptocurrency project that uses blockchain technology for secure transactions",
        tags: ["cloud computing"],
        collaborators: [
            { name: "Faith Maase", image: "/images/avatar/avatar-4.jpg" },
            { name: "Jemmie Drieu", image: undefined },
            { name: "Regine McGiff", image: "/images/avatar/avatar-2.jpg" },
        ],
        progress: 93,
        started_at: "5/17/2022",
        deadline: "9/17/2022",
    },
    {
        project_id: 77,
        partner_image: "/images/logos/flickr-round.svg",
        partner_name: "Sony",
        project_name: "CodeX",
        project_desc:
            "An environmental technology project that promotes sustainability and reduces environmental impact",
        tags: ["IT consulting", "cybersecurity"],
        collaborators: [
            { name: "Ruthanne Grebert", image: "/images/avatar/avatar-18.jpg" },
            { name: "Bogey Albin", image: "/images/avatar/avatar-12.jpg" },
            { name: "Stanton Gornall", image: "/images/avatar/avatar-20.jpg" },
            { name: "Trudie Bambery", image: undefined },
            { name: "Gibbie Pittoli", image: "/images/avatar/avatar-15.jpg" },
        ],
        progress: 53,
        started_at: "3/6/2023",
        deadline: "8/6/2023",
    },
    {
        project_id: 78,
        partner_image: "/images/logos/pinterest-round.svg",
        partner_name: "Nintendo",
        project_name: "DataViz",
        project_desc:
            "A social networking project that connects people and communities",
        tags: ["database management", "virtual reality"],
        collaborators: [
            { name: "Calhoun Rickeard", image: "/images/avatar/avatar-18.jpg" },
            { name: "Isobel Nellis", image: "/images/avatar/avatar-14.jpg" },
        ],
        progress: 77,
        started_at: "7/6/2022",
        deadline: "9/6/2022",
    },
    {
        project_id: 79,
        partner_image: "/images/logos/microsoft.svg",
        partner_name: "Sony",
        project_name: "SmartHome",
        project_desc:
            "An e-commerce project that sells products or services online",
        tags: ["user experience design"],
        collaborators: [{ name: "Augustine Pockey", image: undefined }],
        progress: 95,
        started_at: "4/14/2023",
        deadline: "4/14/2024",
    },
    {
        project_id: 80,
        partner_image: "/images/logos/pinterest-round.svg",
        partner_name: "Razer",
        project_name: "CyberSec",
        project_desc:
            "A media production project that creates and distributes digital content",
        tags: ["user experience design", "Web development", "digital marketing"],
        collaborators: [
            { name: "Myles Capper", image: "/images/avatar/avatar-14.jpg" },
            { name: "Abagael Findlay", image: undefined },
            { name: "Cully Springate", image: "/images/avatar/avatar-15.jpg" },
            { name: "Hertha Baroux", image: "/images/avatar/avatar-12.jpg" },
            { name: "Sergei Housen", image: undefined },
        ],
        progress: 2,
        started_at: "5/1/2023",
        deadline: "5/1/2024",
    },
    {
        project_id: 81,
        partner_image: "/images/logos/google.svg",
        partner_name: "Acer",
        project_name: "ChatBot",
        project_desc: "A platform for collaborative coding and debugging",
        tags: ["digital marketing", "robotics", "IT education"],
        collaborators: [
            { name: "Wendy Ruddiman", image: "/images/avatar/avatar-20.jpg" },
            { name: "Ruthann Todeo", image: undefined },
            { name: "Dallis Vlasenko", image: "/images/avatar/avatar-13.jpg" },
            { name: "Irvine Penhallurick", image: "/images/avatar/avatar-1.jpg" },
        ],
        progress: 37,
        started_at: "2/13/2023",
        deadline: "9/13/2023",
    },
    {
        project_id: 82,
        partner_image: "/images/logos/behance-round.svg",
        partner_name: "Sony",
        project_name: "AIr",
        project_desc:
            "A tool for creating interactive data visualizations and dashboards",
        tags: ["machine learning", "e-commerce"],
        collaborators: [{ name: "Melantha Fayers", image: undefined }],
        progress: 41,
        started_at: "11/16/2022",
        deadline: "8/16/2023",
    },
    {
        project_id: 83,
        partner_image: "/images/logos/behance-round.svg",
        partner_name: "Acer",
        project_name: "WebDev",
        project_desc:
            "A system for controlling and monitoring smart devices in your home",
        tags: ["blockchain"],
        collaborators: [
            { name: "Damaris Witherop", image: "/images/avatar/avatar-19.jpg" },
            { name: "Meara Ledeker", image: "/images/avatar/avatar-13.jpg" },
        ],
        progress: 31,
        started_at: "6/2/2022",
        deadline: "12/2/2022",
    },
    {
        project_id: 84,
        partner_image: "/images/logos/microsoft.svg",
        partner_name: "Acer",
        project_name: "Cloudy",
        project_desc:
            "A system for controlling and monitoring smart devices in your home",
        tags: ["robotics", "system administration"],
        collaborators: [
            { name: "Gottfried Heading", image: "/images/avatar/avatar-3.jpg" },
            { name: "Gaylor Nezey", image: undefined },
            { name: "Cathe Posselt", image: "/images/avatar/avatar-16.jpg" },
            { name: "Henryetta Lowre", image: "/images/avatar/avatar-9.jpg" },
        ],
        progress: 50,
        started_at: "12/2/2022",
        deadline: "7/2/2023",
    },
    {
        project_id: 85,
        partner_image: "/images/logos/adobe_portfolio-round.svg",
        partner_name: "Acer",
        project_name: "VRy",
        project_desc: "A chatbot that can answer questions and provide assistance",
        tags: ["robotics", "technical support", "IT governance and IT strategy."],
        collaborators: [
            { name: "Garold Frandsen", image: "/images/avatar/avatar-4.jpg" },
            { name: "Cindee Stonnell", image: "/images/avatar/avatar-11.jpg" },
        ],
        progress: 12,
        started_at: "3/15/2023",
        deadline: "2/15/2024",
    },
    {
        project_id: 86,
        partner_image: "/images/logos/flickr-round.svg",
        partner_name: "Samsung",
        project_name: "IoTize",
        project_desc:
            "An artificial intelligence system that can recognize and respond to voice commands",
        tags: [
            "user interface design",
            "software engineering",
            "artificial intelligence",
        ],
        collaborators: [
            { name: "Genvieve Bartoleyn", image: "/images/avatar/avatar-4.jpg" },
            { name: "Clarke Edkins", image: "/images/avatar/avatar-13.jpg" },
            { name: "Alvinia Wyles", image: "/images/avatar/avatar-17.jpg" },
            { name: "Bobbee Blackston", image: "/images/avatar/avatar-5.jpg" },
        ],
        progress: 83,
        started_at: "4/26/2023",
        deadline: "8/26/2023",
    },
    {
        project_id: 87,
        partner_image: "/images/logos/pinterest-round.svg",
        partner_name: "Huawei",
        project_name: "BioTech",
        project_desc:
            "A website builder that lets you create and host your own websites",
        tags: ["artificial intelligence"],
        collaborators: [
            { name: "Joya De Luna", image: "/images/avatar/avatar-17.jpg" },
            { name: "Amaleta Bonwick", image: undefined },
            { name: "Raphael Marwick", image: "/images/avatar/avatar-7.jpg" },
        ],
        progress: 13,
        started_at: "5/1/2023",
        deadline: "3/1/2024",
    },
    {
        project_id: 88,
        partner_image: "/images/logos/google.svg",
        partner_name: "Apple",
        project_name: "GameOn",
        project_desc:
            "A cloud computing service that offers storage & computing and networking resources",
        tags: ["user interface design", "database management"],
        collaborators: [
            { name: "Hedy Philipson", image: "/images/avatar/avatar-15.jpg" },
            { name: "Muffin Newsome", image: undefined },
            { name: "Antonietta McCrory", image: "/images/avatar/avatar-15.jpg" },
            { name: "Berta Gomery", image: undefined },
        ],
        progress: 9,
        started_at: "7/4/2022",
        deadline: "2/4/2023",
    },
    {
        project_id: 89,
        partner_image: "/images/logos/flickr-round.svg",
        partner_name: "Razer",
        project_name: "EduTech",
        project_desc:
            "A virtual reality app that lets you explore and create immersive environments",
        tags: ["technical support"],
        collaborators: [
            { name: "Tobi Stegers", image: "/images/avatar/avatar-13.jpg" },
            { name: "Janaye Brader", image: "/images/avatar/avatar-11.jpg" },
            { name: "Jillane Scott", image: undefined },
        ],
        progress: 27,
        started_at: "9/14/2022",
        deadline: "10/14/2022",
    },
    {
        project_id: 90,
        partner_image: "/images/logos/google.svg",
        partner_name: "Nintendo",
        project_name: "FinTech",
        project_desc: "A device that connects any object to the internet of things",
        tags: ["IT consulting", "software engineering"],
        collaborators: [
            { name: "Esme Kellaway", image: "/images/avatar/avatar-7.jpg" },
            { name: "Patsy Stanwix", image: "/images/avatar/avatar-1.jpg" },
            { name: "Edi Dubber", image: "/images/avatar/avatar-14.jpg" },
        ],
        progress: 38,
        started_at: "5/21/2022",
        deadline: "8/21/2022",
    },
    {
        project_id: 91,
        partner_image: "/images/logos/microsoft.svg",
        partner_name: "HP",
        project_name: "HealthIT",
        project_desc:
            "A biotechnology project that uses living organisms or their components for various purposes",
        tags: ["network administration", "internet of things"],
        collaborators: [
            { name: "Kelby Urlich", image: "/images/avatar/avatar-19.jpg" },
        ],
        progress: 66,
        started_at: "8/24/2022",
        deadline: "8/24/2023",
    },
    {
        project_id: 92,
        partner_image: "/images/logos/pinterest-round.svg",
        partner_name: "LG",
        project_name: "GreenIT",
        project_desc:
            "A game development studio that creates and publishes video games",
        tags: ["internet of things", "automation"],
        collaborators: [
            { name: "Cordey Andras", image: "/images/avatar/avatar-1.jpg" },
        ],
        progress: 93,
        started_at: "7/28/2022",
        deadline: "9/28/2022",
    },
    {
        project_id: 93,
        partner_image: "/images/logos/google.svg",
        partner_name: "Huawei",
        project_name: "SocialNet",
        project_desc:
            "An educational technology project that enhances learning and teaching",
        tags: ["database management", "technical support"],
        collaborators: [
            { name: "Urban Oatley", image: "/images/avatar/avatar-18.jpg" },
        ],
        progress: 96,
        started_at: "11/20/2022",
        deadline: "4/20/2023",
    },
    {
        project_id: 94,
        partner_image: "/images/logos/adobe_portfolio-round.svg",
        partner_name: "Lenovo",
        project_name: "Ecom",
        project_desc:
            "A financial technology project that provides innovative solutions for banking and finance",
        tags: ["graphic design", "cloud computing"],
        collaborators: [
            { name: "Sheri McGeachey", image: undefined },
            { name: "Lexie Gadsden", image: "/images/avatar/avatar-4.jpg" },
            { name: "Alleen Soar", image: undefined },
            { name: "Carissa McSpirron", image: "/images/avatar/avatar-2.jpg" },
            { name: "Woodrow Iles", image: "/images/avatar/avatar-7.jpg" },
        ],
        progress: 97,
        started_at: "6/18/2022",
        deadline: "2/18/2023",
    },
    {
        project_id: 95,
        partner_image: "/images/logos/adobe_portfolio-round.svg",
        partner_name: "Dell",
        project_name: "MediaLab",
        project_desc:
            "A health information technology project that improves health care delivery and outcomes",
        tags: ["IT audit"],
        collaborators: [
            { name: "Halli Schoales", image: "/images/avatar/avatar-11.jpg" },
        ],
        progress: 28,
        started_at: "3/9/2023",
        deadline: "2/9/2024",
    },
    {
        project_id: 96,
        partner_image: "/images/logos/flickr-round.svg",
        partner_name: "Dell",
        project_name: "CodeX",
        project_desc:
            "A cryptocurrency project that uses blockchain technology for secure transactions",
        tags: ["mobile app development"],
        collaborators: [
            { name: "Graeme Wass", image: "/images/avatar/avatar-3.jpg" },
            { name: "Siobhan McKimm", image: "/images/avatar/avatar-7.jpg" },
            { name: "Phyllida Micklewicz", image: "/images/avatar/avatar-1.jpg" },
            { name: "Norbie Squibbes", image: "/images/avatar/avatar-15.jpg" },
            { name: "Darrin Gallamore", image: undefined },
        ],
        progress: 9,
        started_at: "4/27/2023",
        deadline: "1/27/2024",
    },
    {
        project_id: 97,
        partner_image: "/images/logos/microsoft.svg",
        partner_name: "Asus",
        project_name: "DataViz",
        project_desc:
            "An environmental technology project that promotes sustainability and reduces environmental impact",
        tags: ["cybersecurity", "database management", "cloud computing"],
        collaborators: [
            { name: "Jessie Heaven", image: "/images/avatar/avatar-20.jpg" },
        ],
        progress: 89,
        started_at: "10/25/2022",
        deadline: "9/25/2023",
    },
    {
        project_id: 98,
        partner_image: "/images/logos/microsoft.svg",
        partner_name: "Sony",
        project_name: "SmartHome",
        project_desc:
            "A social networking project that connects people and communities",
        tags: ["IT governance and IT strategy.", "system administration"],
        collaborators: [
            { name: "Jolee Dudek", image: "/images/avatar/avatar-5.jpg" },
            { name: "Alethea Jindracek", image: "/images/avatar/avatar-4.jpg" },
        ],
        progress: 79,
        started_at: "3/8/2023",
        deadline: "1/8/2024",
    },
    {
        project_id: 99,
        partner_image: "/images/logos/pinterest-round.svg",
        partner_name: "Microsoft",
        project_name: "CyberSec",
        project_desc:
            "An e-commerce project that sells products or services online",
        tags: ["IT consulting"],
        collaborators: [
            { name: "Galvin Mayer", image: "/images/avatar/avatar-7.jpg" },
            { name: "Ramona Verbrugge", image: "/images/avatar/avatar-11.jpg" },
            { name: "Quinlan Reuven", image: "/images/avatar/avatar-19.jpg" },
            { name: "Callie Clutten", image: undefined },
            { name: "Addi Tyhurst", image: undefined },
        ],
        progress: 53,
        started_at: "3/1/2023",
        deadline: "5/1/2023",
    },
    {
        project_id: 100,
        partner_image: "/images/logos/flickr-round.svg",
        partner_name: "Nintendo",
        project_name: "ChatBot",
        project_desc:
            "A media production project that creates and distributes digital content",
        tags: ["Web development", "user interface design"],
        collaborators: [
            { name: "Sianna L'Archer", image: "/images/avatar/avatar-3.jpg" },
            { name: "Silvester Helis", image: undefined },
        ],
        progress: 92,
        started_at: "1/16/2023",
        deadline: "7/16/2023",
    },
];
