export interface User {
  uid: string;
  name: string;
  avatar?: string | null;
  email: string;
  website: string;
  phone: string;
  position: string;
  isOnline: boolean;
}

export const users: User[] = [
  {
    uid: "1",
    name: "Chiquita Flament",
    avatar: "/images/avatar/avatar-6.jpg",
    email: "cflament0@foxnews.com",
    website: "www.foxnews.com",
    phone: "312-329-5963",
    position: "Backend Developer",
    isOnline: true,
  },
  {
    uid: "2",
    name: "Ludvig Kennea",
    avatar: "/images/avatar/avatar-12.jpg",
    email: "lkennea1@nydailynews.com",
    website: "www.nydailynews.com",
    phone: "398-181-0799",
    position: "Frontend Developer",
    isOnline: true,
  },
  {
    uid: "3",
    name: "Kelvin Keuning",
    avatar: "/images/avatar/avatar-20.jpg",
    email: "kkeuning2@nih.gov",
    website: "www.nih.gov",
    phone: "177-302-1065",
    position: "UI/UX Designer",
    isOnline: true,
  },
  {
    uid: "4",
    name: "Homere O'Noulane",
    avatar: "/images/avatar/avatar-11.jpg",
    email: "honoulane3@goo.ne.jp",
    website: "www.goo.ne.jp",
    phone: "673-942-1852",
    position: "Web Developer",
    isOnline: false,
  },
  {
    uid: "5",
    name: "Kriste Salerno",
    avatar: null,
    email: "ksalerno4@amazonaws.com",
    website: "www.amazonaws.com",
    phone: "355-451-1490",
    position: "Commercial Director",
    isOnline: true,
  },
  {
    uid: "6",
    name: "Georgianna Lancett",
    avatar: "/images/avatar/avatar-10.jpg",
    email: "glancett5@w3.org",
    website: "www.w3.org",
    phone: "957-842-2732",
    position: "HR",
    isOnline: true,
  },
  {
    uid: "7",
    name: "Elissa Hunter",
    avatar: "/images/avatar/avatar-10.jpg",
    email: "ehunter6@cocolog-nifty.com",
    website: "www.cocolog-nifty.com",
    phone: "791-332-3620",
    position: "Software Engineer",
    isOnline: true,
  },
  {
    uid: "8",
    name: "Melvin Fynan",
    avatar: null,
    email: "mfynan7@photobucket.com",
    website: "www.photobucket.com",
    phone: "231-966-7454",
    position: "IOS Developer",
    isOnline: true,
  },
  {
    uid: "9",
    name: "Cooper Hanfrey",
    avatar: "/images/avatar/avatar-17.jpg",
    email: "chanfrey8@indiatimes.com",
    website: "www.indiatimes.com",
    phone: "853-318-1593",
    position: "Full Stack Developer",
    isOnline: false,
  },
  {
    uid: "10",
    name: "Isobel Beininck",
    avatar: null,
    email: "ibeininck9@smugmug.com",
    website: "www.smugmug.com",
    phone: "952-500-0727",
    position: "Android Developer",
    isOnline: true,
  },
  {
    uid: "11",
    name: "Arlen Guyonneau",
    avatar: "/images/avatar/avatar-17.jpg",
    email: "aguyonneaua@apple.com",
    website: "www.apple.com",
    phone: "173-834-9691",
    position: "Senior Developer",
    isOnline: true,
  },
  {
    uid: "12",
    name: "Erda Matyja",
    avatar: "/images/avatar/avatar-14.jpg",
    email: "ematyjab@sbwire.com",
    website: "www.sbwire.com",
    phone: "762-437-1668",
    position: "Laravel Developer",
    isOnline: true,
  },
];
