import { ColorType } from "@/constants/app";

import {
  ArrowPathIcon,
  CheckBadgeIcon,
  ClockIcon,
  TruckIcon,
  XCircleIcon,
} from "@heroicons/react/24/outline";

interface StatusOption {
  value: string;
  label: string;
  color: ColorType;
  icon: React.ElementType;
}

interface Customer {
  name: string;
  avatar_img: string | null;
  customer_id: string;
}

interface ShippingAddress {
  street: string;
  line: string;
}

interface Product {
  name: string;
  sku: number;
  image: string;
  price: number;
  qty: number;
  discount: number;
  total: number;
  product_id: string;
}

export type PaymentStatus = "paid" | "pending" | "failed";

export type OrderStatus =
  | "shipping"
  | "pending"
  | "completed"
  | "processing"
  | "cancelled";

export interface Order {
  order_id: string;
  created_at: string;
  customer: Customer;
  total: number;
  profit: number;
  payment_status: PaymentStatus;
  order_status: OrderStatus;
  shipping_address: ShippingAddress;
  products: Product[];
  subtotal: number;
  delivery_fee: number;
  tax: number;
  total_amount_due: number;
}

export const orderStatusOptions: StatusOption[] = [
  {
    value: "shipping",
    label: "Shipping",
    color: "info",
    icon: TruckIcon,
  },
  {
    value: "pending",
    label: "Pending",
    color: "warning",
    icon: ClockIcon,
  },
  {
    value: "completed",
    label: "Completed",
    color: "success",
    icon: CheckBadgeIcon,
  },
  {
    value: "processing",
    label: "Processing",
    color: "primary",
    icon: ArrowPathIcon,
  },
  {
    value: "cancelled",
    label: "Cancelled",
    color: "error",
    icon: XCircleIcon,
  },
];

export const ordersList: Order[] = [
  {
    order_id: "#63858",
    created_at: "1676070562000",
    customer: {
      name: "Henka Scanes",
      avatar_img: null,
      customer_id: "CUST-a7b2c3d4", 
    },
    total: 944.82,
    profit: 415.7208,
    payment_status: "paid",
    order_status: "shipping",
    shipping_address: { street: "6 Algoma Crossing", line: "PO Box 92517" },
    products: [
      {
        name: "Salmon - Whole, 4 - 6 Pounds",
        sku: 58988,
        image: "/images/products/product-7.jpg",
        price: 280.65,
        qty: 1,
        discount: 0.52,
        total: 235.58,
        product_id: "PROD-a1b2c3d4", 
      },
      {
        name: "Veal - Shank, Pieces",
        sku: 44640,
        image: "/images/products/product-3.jpg",
        price: 59.77,
        qty: 3,
        discount: 0.45,
        total: 946.77,
        product_id: "PROD-e5f6g7h8", 
      },
      {
        name: "Calypso - Pineapple Passion",
        sku: 27758,
        image: "/images/products/product-11.jpg",
        price: 771.2,
        qty: 6,
        discount: 0.5,
        total: 182.33,
        product_id: "PROD-i9j0k1l2", 
      },
      {
        name: "Wine - Bourgogne 2002, La",
        sku: 5777,
        image: "/images/products/product-5.jpg",
        price: 958.47,
        qty: 7,
        discount: 0.03,
        total: 138.03,
        product_id: "PROD-m3n4o5p6", 
      },
      {
        name: "Scrubbie - Scotchbrite Hand Pad",
        sku: 47120,
        image: "/images/products/product-3.jpg",
        price: 733.53,
        qty: 7,
        discount: 0.54,
        total: 633.73,
        product_id: "PROD-q7r8s9t0", 
      },
    ],
    subtotal: 24.74,
    delivery_fee: 86.62,
    tax: 20,
    total_amount_due: 866.51,
  },
  {
    order_id: "#39977",
    created_at: "1671216009000",
    customer: {
      name: "Larine Burgher",
      avatar_img: "/images/avatar/avatar-12.jpg",
      customer_id: "CUST-002",
    },
    total: 836.63,
    profit: 359.7509,
    payment_status: "pending",
    order_status: "processing",
    shipping_address: { street: "42023 Acker Plaza", line: "Suite 4" },
    products: [
      {
        name: "Soup - Campbells, Spinach Crm",
        sku: 45606,
        image: "/images/products/product-10.jpg",
        price: 871.47,
        qty: 6,
        discount: 0.0,
        total: 602.74,
        product_id: "PROD-006",
      },
      {
        name: "Vodka - Hot, Lnferno",
        sku: 63567,
        image: "/images/products/product-10.jpg",
        price: 17.29,
        qty: 4,
        discount: 0.34,
        total: 697.67,
        product_id: "PROD-007",
      },
      {
        name: "Melon - Cantaloupe",
        sku: 52265,
        image: "/images/products/product-12.jpg",
        price: 98.37,
        qty: 7,
        discount: 0.11,
        total: 768.91,
        product_id: "PROD-008",
      },
      {
        name: "Pomello",
        sku: 66346,
        image: "/images/products/product-12.jpg",
        price: 781.36,
        qty: 6,
        discount: 0.29,
        total: 662.79,
        product_id: "PROD-009",
      },
      {
        name: "Cucumber - English",
        sku: 82432,
        image: "/images/products/product-3.jpg",
        price: 553.61,
        qty: 1,
        discount: 0.35,
        total: 323.88,
        product_id: "PROD-010",
      },
      {
        name: "Beer - Fruli",
        sku: 24951,
        image: "/images/products/product-6.jpg",
        price: 523.62,
        qty: 1,
        discount: 0.1,
        total: 232.41,
        product_id: "PROD-011",
      },
    ],
    subtotal: 586.93,
    delivery_fee: 76.06,
    tax: 20,
    total_amount_due: 226.78,
  },
  {
    order_id: "#28807",
    created_at: "1667534249000",
    customer: {
      name: "Aguste Lutty",
      avatar_img: "/images/avatar/avatar-18.jpg",
      customer_id: "CUST-003",
    },
    total: 391.17,
    profit: 226.8786,
    payment_status: "failed",
    order_status: "shipping",
    shipping_address: { street: "4955 Kingsford Point", line: "PO Box 30647" },
    products: [
      {
        name: "Puree - Mango",
        sku: 78737,
        image: "/images/products/product-1.jpg",
        price: 97.71,
        qty: 5,
        discount: 0.29,
        total: 12.45,
        product_id: "PROD-012",
      },
      {
        name: "Beer - Heinekin",
        sku: 23547,
        image: "/images/products/product-5.jpg",
        price: 658.22,
        qty: 9,
        discount: 0.13,
        total: 147.12,
        product_id: "PROD-013",
      },
      {
        name: "Squid U5 - Thailand",
        sku: 43161,
        image: "/images/products/product-4.jpg",
        price: 504.07,
        qty: 9,
        discount: 0.14,
        total: 698.09,
        product_id: "PROD-014",
      },
    ],
    subtotal: 981.96,
    delivery_fee: 60.87,
    tax: 20,
    total_amount_due: 432.77,
  },
  {
    order_id: "#98000",
    created_at: "1660978592000",
    customer: {
      name: "Annalise Raff",
      avatar_img: "/images/avatar/avatar-20.jpg",
      customer_id: "CUST-004",
    },
    total: 82.24,
    profit: 28.784,
    payment_status: "failed",
    order_status: "shipping",
    shipping_address: { street: "13597 Everett Terrace", line: "Room 216" },
    products: [
      {
        name: "Cup - Translucent 7 Oz Clear",
        sku: 62071,
        image: "/images/products/product-1.jpg",
        price: 96.75,
        qty: 3,
        discount: 0.14,
        total: 87.49,
        product_id: "PROD-015",
      },
      {
        name: "Clams - Canned",
        sku: 22892,
        image: "/images/products/product-10.jpg",
        price: 1.02,
        qty: 5,
        discount: 0.14,
        total: 405.0,
        product_id: "PROD-016",
      },
      {
        name: "Soup - Campbells, Spinach Crm",
        sku: 43743,
        image: "/images/products/product-9.jpg",
        price: 891.83,
        qty: 8,
        discount: 0.18,
        total: 985.36,
        product_id: "PROD-017",
      },
      {
        name: "Sping Loaded Cup Dispenser",
        sku: 86700,
        image: "/images/products/product-11.jpg",
        price: 565.8,
        qty: 8,
        discount: 0.47,
        total: 272.62,
        product_id: "PROD-018",
      },
      {
        name: "Wine - Magnotta - Belpaese",
        sku: 10261,
        image: "/images/products/product-1.jpg",
        price: 28.79,
        qty: 0,
        discount: 0.51,
        total: 327.43,
        product_id: "PROD-019",
      },
    ],
    subtotal: 288.8,
    delivery_fee: 52.51,
    tax: 20,
    total_amount_due: 654.0,
  },
  {
    order_id: "#20904",
    created_at: "1652615280000",
    customer: {
      name: "Ashbey Cuddehy",
      avatar_img: null,
      customer_id: "CUST-005",
    },
    total: 470.1,
    profit: 23.505,
    payment_status: "paid",
    order_status: "pending",
    shipping_address: { street: "73771 Dawn Hill", line: "PO Box 54935" },
    products: [
      {
        name: "Ice Cream - Super Sandwich",
        sku: 9828,
        image: "/images/products/product-9.jpg",
        price: 481.19,
        qty: 6,
        discount: 0.19,
        total: 106.61,
        product_id: "PROD-020",
      },
      {
        name: "Garlic - Primerba, Paste",
        sku: 96283,
        image: "/images/products/product-4.jpg",
        price: 110.12,
        qty: 0,
        discount: 0.0,
        total: 845.41,
        product_id: "PROD-021",
      },
    ],
    subtotal: 346.63,
    delivery_fee: 99.58,
    tax: 20,
    total_amount_due: 9.04,
  },
  {
    order_id: "#60431",
    created_at: "1653476416000",
    customer: {
      name: "Winston Marlin",
      avatar_img: "/images/avatar/avatar-3.jpg",
      customer_id: "CUST-j94igrf2",
    },
    total: 13.83,
    profit: 7.7448,
    payment_status: "failed",
    order_status: "completed",
    shipping_address: { street: "2691 Rieder Avenue", line: "4th Floor" },
    products: [
      {
        name: "Sauce - Plum",
        sku: 34476,
        image: "/images/products/product-3.jpg",
        price: 398.23,
        qty: 10,
        discount: 0.04,
        total: 506.63,
        product_id: "PROD-chu8nasm",
      },
      {
        name: "Bread - Kimel Stick Poly",
        sku: 29083,
        image: "/images/products/product-2.jpg",
        price: 590.26,
        qty: 7,
        discount: 0.56,
        total: 572.78,
        product_id: "PROD-euv7399r",
      },
      {
        name: "Tuna - Bluefin",
        sku: 5328,
        image: "/images/products/product-10.jpg",
        price: 835.03,
        qty: 7,
        discount: 0.05,
        total: 197.13,
        product_id: "PROD-z8nxk8v5",
      },
      {
        name: "Pepsi - 600ml",
        sku: 47835,
        image: "/images/products/product-5.jpg",
        price: 114.31,
        qty: 3,
        discount: 0.5,
        total: 943.34,
        product_id: "PROD-l3x0ytne",
      },
    ],
    subtotal: 613.45,
    delivery_fee: 60.72,
    tax: 20,
    total_amount_due: 89.53,
  },
  {
    order_id: "#10670",
    created_at: "1657970287000",
    customer: {
      name: "Zandra Bilbey",
      avatar_img: "/images/avatar/avatar-7.jpg",
      customer_id: "CUST-r4vutfym",
    },
    total: 223.3,
    profit: 82.621,
    payment_status: "pending",
    order_status: "processing",
    shipping_address: { street: "118 Kim Crossing", line: "Room 1682" },
    products: [
      {
        name: "Salmon - Whole, 4 - 6 Pounds",
        sku: 58988,
        image: "/images/products/product-7.jpg",
        price: 280.65,
        qty: 1,
        discount: 0.52,
        total: 235.58,
        product_id: "PROD-lbc6zbdi",
      },
      {
        name: "Veal - Shank, Pieces",
        sku: 44640,
        image: "/images/products/product-3.jpg",
        price: 59.77,
        qty: 3,
        discount: 0.45,
        total: 946.77,
        product_id: "PROD-ij0kur6e",
      },
      {
        name: "Calypso - Pineapple Passion",
        sku: 27758,
        image: "/images/products/product-11.jpg",
        price: 771.2,
        qty: 6,
        discount: 0.5,
        total: 182.33,
        product_id: "PROD-nfornav1",
      },
      {
        name: "Pie Box - Cello Window 2.5",
        sku: 42045,
        image: "/images/products/product-5.jpg",
        price: 674.85,
        qty: 1,
        discount: 0.48,
        total: 39.91,
        product_id: "PROD-567zxgwz",
      },
      {
        name: "Wine - Bourgogne 2002, La",
        sku: 5777,
        image: "/images/products/product-5.jpg",
        price: 958.47,
        qty: 7,
        discount: 0.03,
        total: 138.03,
        product_id: "PROD-9e7xarzp",
      },
      {
        name: "Scrubbie - Scotchbrite Hand Pad",
        sku: 47120,
        image: "/images/products/product-3.jpg",
        price: 733.53,
        qty: 7,
        discount: 0.54,
        total: 633.73,
        product_id: "PROD-0w04rz3h",
      },
    ],
    subtotal: 209.13,
    delivery_fee: 66.69,
    tax: 20,
    total_amount_due: 2.11,
  },
  {
    order_id: "#68469",
    created_at: "1674280737000",
    customer: {
      name: "Bal Andrat",
      avatar_img: null,
      customer_id: "CUST-8g11ty2u",
    },
    total: 84.0,
    profit: 21.84,
    payment_status: "paid",
    order_status: "shipping",
    shipping_address: { street: "195 Mosinee Junction", line: "Room 566" },
    products: [
      {
        name: "Turkey Leg With Drum And Thigh",
        sku: 43192,
        image: "/images/products/product-5.jpg",
        price: 354.36,
        qty: 6,
        discount: 0.27,
        total: 369.89,
        product_id: "PROD-yhb46hpd",
      },
      {
        name: "Wine - Prosecco Valdobiaddene",
        sku: 88559,
        image: "/images/products/product-10.jpg",
        price: 915.27,
        qty: 6,
        discount: 0.44,
        total: 788.42,
        product_id: "PROD-zevgfo8n",
      },
      {
        name: "Pasta - Cheese / Spinach Bauletti",
        sku: 63158,
        image: "/images/products/product-10.jpg",
        price: 129.27,
        qty: 2,
        discount: 0.22,
        total: 80.3,
        product_id: "PROD-fxyw6wzf",
      },
      {
        name: "Mace",
        sku: 49351,
        image: "/images/products/product-9.jpg",
        price: 800.69,
        qty: 4,
        discount: 0.11,
        total: 641.32,
        product_id: "PROD-ufieks3l",
      },
      {
        name: "Oneshot Automatic Soap System",
        sku: 35926,
        image: "/images/products/product-5.jpg",
        price: 710.24,
        qty: 9,
        discount: 0.09,
        total: 751.22,
        product_id: "PROD-5gb1gkl8",
      },
      {
        name: "Veal - Heart",
        sku: 50381,
        image: "/images/products/product-8.jpg",
        price: 75.22,
        qty: 3,
        discount: 0.23,
        total: 772.78,
        product_id: "PROD-1lqwlalo",
      },
      {
        name: "Yucca",
        sku: 79018,
        image: "/images/products/product-8.jpg",
        price: 976.07,
        qty: 8,
        discount: 0.12,
        total: 237.89,
        product_id: "PROD-un9ik2kb",
      },
    ],
    subtotal: 879.16,
    delivery_fee: 11.89,
    tax: 20,
    total_amount_due: 304.34,
  },
  {
    order_id: "#53706",
    created_at: "1667851780000",
    customer: {
      name: "Suzann Tall",
      avatar_img: "/images/avatar/avatar-4.jpg",
      customer_id: "CUST-7vc8jw9d",
    },
    total: 44.86,
    profit: 2.243,
    payment_status: "pending",
    order_status: "shipping",
    shipping_address: { street: "60 Messerschmidt Avenue", line: "2nd Floor" },
    products: [
      {
        name: "Hagen Daza - Dk Choocolate",
        sku: 23304,
        image: "/images/products/product-10.jpg",
        price: 253.85,
        qty: 0,
        discount: 0.25,
        total: 230.41,
        product_id: "PROD-8ri7lpyy",
      },
      {
        name: "Pasta - Spaghetti, Dry",
        sku: 95335,
        image: "/images/products/product-10.jpg",
        price: 887.98,
        qty: 3,
        discount: 0.27,
        total: 437.17,
        product_id: "PROD-9l9h8qee",
      },
      {
        name: "Ecolab Digiclean Mild Fm",
        sku: 75890,
        image: "/images/products/product-2.jpg",
        price: 488.74,
        qty: 8,
        discount: 0.51,
        total: 826.13,
        product_id: "PROD-veadws63",
      },
      {
        name: "Shrimp - 16/20, Iqf, Shell On",
        sku: 98308,
        image: "/images/products/product-7.jpg",
        price: 867.72,
        qty: 6,
        discount: 0.17,
        total: 532.41,
        product_id: "PROD-mivvnfq3",
      },
    ],
    subtotal: 994.86,
    delivery_fee: 59.66,
    tax: 20,
    total_amount_due: 346.62,
  },
  {
    order_id: "#89429",
    created_at: "1657378671000",
    customer: {
      name: "Kassie Feldon",
      avatar_img: "/images/avatar/avatar-3.jpg",
      customer_id: "CUST-vd8umul6",
    },
    total: 994.03,
    profit: 59.6418,
    payment_status: "failed",
    order_status: "cancelled",
    shipping_address: { street: "0660 Fisk Park", line: "Room 620" },
    products: [
      {
        name: "Salmon - Whole, 4 - 6 Pounds",
        sku: 58988,
        image: "/images/products/product-7.jpg",
        price: 280.65,
        qty: 1,
        discount: 0.52,
        total: 235.58,
        product_id: "PROD-d1syt2y2",
      },
      {
        name: "Veal - Shank, Pieces",
        sku: 44640,
        image: "/images/products/product-3.jpg",
        price: 59.77,
        qty: 3,
        discount: 0.45,
        total: 946.77,
        product_id: "PROD-vbv3l05d",
      },
      {
        name: "Calypso - Pineapple Passion",
        sku: 27758,
        image: "/images/products/product-11.jpg",
        price: 771.2,
        qty: 6,
        discount: 0.5,
        total: 182.33,
        product_id: "PROD-lz36iri7",
      },
      {
        name: "Pie Box - Cello Window 2.5",
        sku: 42045,
        image: "/images/products/product-5.jpg",
        price: 674.85,
        qty: 1,
        discount: 0.48,
        total: 39.91,
        product_id: "PROD-mbai405v",
      },
      {
        name: "Wine - Bourgogne 2002, La",
        sku: 5777,
        image: "/images/products/product-5.jpg",
        price: 958.47,
        qty: 7,
        discount: 0.03,
        total: 138.03,
        product_id: "PROD-si9qkak5",
      },
      {
        name: "Scrubbie - Scotchbrite Hand Pad",
        sku: 47120,
        image: "/images/products/product-3.jpg",
        price: 733.53,
        qty: 7,
        discount: 0.54,
        total: 633.73,
        product_id: "PROD-gmbjtr39",
      },
    ],
    subtotal: 834.52,
    delivery_fee: 51.53,
    tax: 20,
    total_amount_due: 961.13,
  },
  {
    order_id: "#87112",
    created_at: "1675469887000",
    customer: {
      name: "Milty Dummigan",
      avatar_img: "/images/avatar/avatar-15.jpg",
      customer_id: "CUST-nakzpdaj",
    },
    total: 642.33,
    profit: 109.1961,
    payment_status: "paid",
    order_status: "cancelled",
    shipping_address: { street: "361 Mcbride Circle", line: "13th Floor" },
    products: [
      {
        name: "Salmon - Whole, 4 - 6 Pounds",
        sku: 58988,
        image: "/images/products/product-7.jpg",
        price: 280.65,
        qty: 1,
        discount: 0.52,
        total: 235.58,
        product_id: "PROD-j7hsm7qo",
      },
      {
        name: "Veal - Shank, Pieces",
        sku: 44640,
        image: "/images/products/product-3.jpg",
        price: 59.77,
        qty: 3,
        discount: 0.45,
        total: 946.77,
        product_id: "PROD-sk6y16ch",
      },
      {
        name: "Calypso - Pineapple Passion",
        sku: 27758,
        image: "/images/products/product-11.jpg",
        price: 771.2,
        qty: 6,
        discount: 0.5,
        total: 182.33,
        product_id: "PROD-b3ug2hm3",
      },
      {
        name: "Pie Box - Cello Window 2.5",
        sku: 42045,
        image: "/images/products/product-5.jpg",
        price: 674.85,
        qty: 1,
        discount: 0.48,
        total: 39.91,
        product_id: "PROD-hsmuanxm",
      },
      {
        name: "Wine - Bourgogne 2002, La",
        sku: 5777,
        image: "/images/products/product-5.jpg",
        price: 958.47,
        qty: 7,
        discount: 0.03,
        total: 138.03,
        product_id: "PROD-fvdxqysr",
      },
      {
        name: "Scrubbie - Scotchbrite Hand Pad",
        sku: 47120,
        image: "/images/products/product-3.jpg",
        price: 733.53,
        qty: 7,
        discount: 0.54,
        total: 633.73,
        product_id: "PROD-yai9oqv3",
      },
    ],
    subtotal: 280.32,
    delivery_fee: 10.43,
    tax: 20,
    total_amount_due: 828.48,
  },
  {
    order_id: "#43658",
    created_at: "1653437378000",
    customer: {
      name: "Cordie Babon",
      avatar_img: null,
      customer_id: "CUST-k4f70jjv",
    },
    total: 804.12,
    profit: 458.3484,
    payment_status: "paid",
    order_status: "completed",
    shipping_address: { street: "92 Petterle Circle", line: "Suite 12" },
    products: [
      {
        name: "Jameson Irish Whiskey",
        sku: 75769,
        image: "/images/products/product-10.jpg",
        price: 927.31,
        qty: 4,
        discount: 0.07,
        total: 475.12,
        product_id: "PROD-8ced6y7c",
      },
      {
        name: "Napkin White",
        sku: 14804,
        image: "/images/products/product-1.jpg",
        price: 465.64,
        qty: 10,
        discount: 0.53,
        total: 681.97,
        product_id: "PROD-chpzyuwv",
      },
      {
        name: "Sour Puss - Tangerine",
        sku: 3617,
        image: "/images/products/product-3.jpg",
        price: 695.22,
        qty: 10,
        discount: 0.43,
        total: 359.41,
        product_id: "PROD-i0nzr59g",
      },
      {
        name: "Pork - Sausage Casing",
        sku: 24446,
        image: "/images/products/product-7.jpg",
        price: 731.13,
        qty: 0,
        discount: 0.41,
        total: 972.01,
        product_id: "PROD-xc87m7x0",
      },
    ],
    subtotal: 850.8,
    delivery_fee: 96.94,
    tax: 20,
    total_amount_due: 700.99,
  },
  {
    order_id: "#82185",
    created_at: "1678916453000",
    customer: {
      name: "Lani Varah",
      avatar_img: "/images/avatar/avatar-5.jpg",
      customer_id: "CUST-x4x1hwuz",
    },
    total: 24.16,
    profit: 2.6576,
    payment_status: "failed",
    order_status: "completed",
    shipping_address: { street: "5023 Weeping Birch Drive", line: "Room 1869" },
    products: [
      {
        name: "Honey - Lavender",
        sku: 3187,
        image: "/images/products/product-1.jpg",
        price: 580.31,
        qty: 2,
        discount: 0.12,
        total: 37.34,
        product_id: "PROD-a1873zow",
      },
      {
        name: "Amaretto",
        sku: 38171,
        image: "/images/products/product-12.jpg",
        price: 349.29,
        qty: 3,
        discount: 0.15,
        total: 10.3,
        product_id: "PROD-h9aa0cfi",
      },
      {
        name: "Tandoori Curry Paste",
        sku: 5079,
        image: "/images/products/product-6.jpg",
        price: 411.97,
        qty: 3,
        discount: 0.18,
        total: 617.24,
        product_id: "PROD-ux6bbtea",
      },
      {
        name: "Garlic - Peeled",
        sku: 25482,
        image: "/images/products/product-3.jpg",
        price: 662.07,
        qty: 3,
        discount: 0.15,
        total: 635.44,
        product_id: "PROD-sobvjnqf",
      },
      {
        name: "Wine - Spumante Bambino White",
        sku: 45529,
        image: "/images/products/product-9.jpg",
        price: 45.02,
        qty: 2,
        discount: 0.3,
        total: 87.08,
        product_id: "PROD-71c57y5w",
      },
      {
        name: "Cheese - Havarti, Salsa",
        sku: 29878,
        image: "/images/products/product-4.jpg",
        price: 612.39,
        qty: 2,
        discount: 0.46,
        total: 31.7,
        product_id: "PROD-omf0jrrw",
      },
      {
        name: "Veal - Insides, Grains",
        sku: 79668,
        image: "/images/products/product-2.jpg",
        price: 887.24,
        qty: 3,
        discount: 0.31,
        total: 548.09,
        product_id: "PROD-76da13uz",
      },
      {
        name: "Aspic - Clear",
        sku: 97070,
        image: "/images/products/product-10.jpg",
        price: 281.28,
        qty: 5,
        discount: 0.4,
        total: 778.38,
        product_id: "PROD-pba90jf6",
      },
      {
        name: "Tomatoes - Diced, Canned",
        sku: 79069,
        image: "/images/products/product-4.jpg",
        price: 539.35,
        qty: 7,
        discount: 0.53,
        total: 149.51,
        product_id: "PROD-cwl9f4bu",
      },
      {
        name: "Asparagus - Mexican",
        sku: 81585,
        image: "/images/products/product-7.jpg",
        price: 225.35,
        qty: 8,
        discount: 0.47,
        total: 213.72,
        product_id: "PROD-47ify6qo",
      },
    ],
    subtotal: 466.59,
    delivery_fee: 71.24,
    tax: 20,
    total_amount_due: 341.3,
  },
  {
    order_id: "#13585",
    created_at: "1676677964000",
    customer: {
      name: "Hymie Pfaffe",
      avatar_img: "/images/avatar/avatar-18.jpg",
      customer_id: "CUST-6r9pe9x0",
    },
    total: 43.84,
    profit: 11.8368,
    payment_status: "paid",
    order_status: "shipping",
    shipping_address: { street: "288 Steensland Street", line: "Suite 93" },
    products: [
      {
        name: "Wasabi Paste",
        sku: 61776,
        image: "/images/products/product-10.jpg",
        price: 409.75,
        qty: 1,
        discount: 0.43,
        total: 525.95,
        product_id: "PROD-t5hi7c3x",
      },
      {
        name: "Chocolate - Semi Sweet, Calets",
        sku: 21429,
        image: "/images/products/product-1.jpg",
        price: 826.98,
        qty: 10,
        discount: 0.6,
        total: 783.31,
        product_id: "PROD-kwn20l0m",
      },
      {
        name: "Crab - Dungeness, Whole",
        sku: 56656,
        image: "/images/products/product-6.jpg",
        price: 898.75,
        qty: 0,
        discount: 0.37,
        total: 49.06,
        product_id: "PROD-ejcwztjx",
      },
      {
        name: "Oil - Shortening,liqud, Fry",
        sku: 50611,
        image: "/images/products/product-5.jpg",
        price: 545.87,
        qty: 6,
        discount: 0.33,
        total: 983.56,
        product_id: "PROD-7vf1x2l8",
      },
      {
        name: "Beef - Rib Eye Aaa",
        sku: 75645,
        image: "/images/products/product-1.jpg",
        price: 467.21,
        qty: 5,
        discount: 0.22,
        total: 157.61,
        product_id: "PROD-fju76tgx",
      },
      {
        name: "Pickle - Dill",
        sku: 31631,
        image: "/images/products/product-1.jpg",
        price: 66.54,
        qty: 5,
        discount: 0.53,
        total: 904.2,
        product_id: "PROD-vnuz2wvb",
      },
      {
        name: "Wine - Beringer Founders Estate",
        sku: 80706,
        image: "/images/products/product-10.jpg",
        price: 154.85,
        qty: 6,
        discount: 0.01,
        total: 556.82,
        product_id: "PROD-wswo7iqd",
      },
      {
        name: "Ice Cream - Strawberry",
        sku: 97528,
        image: "/images/products/product-7.jpg",
        price: 820.38,
        qty: 10,
        discount: 0.01,
        total: 844.91,
        product_id: "PROD-tdunnw1n",
      },
    ],
    subtotal: 600.12,
    delivery_fee: 70.78,
    tax: 20,
    total_amount_due: 490.97,
  },
  {
    order_id: "#80469",
    created_at: "1669259356000",
    customer: {
      name: "Zola Dayborne",
      avatar_img: "/images/avatar/avatar-20.jpg",
      customer_id: "CUST-0y8lxi5v",
    },
    total: 815.07,
    profit: 57.0549,
    payment_status: "failed",
    order_status: "shipping",
    shipping_address: { street: "444 Memorial Alley", line: "Room 1495" },
    products: [
      {
        name: "Rosemary - Primerba, Paste",
        sku: 83433,
        image: "/images/products/product-1.jpg",
        price: 477.14,
        qty: 8,
        discount: 0.28,
        total: 857.68,
        product_id: "PROD-sp1oun9y",
      },
      {
        name: "Tomatoes Tear Drop Yellow",
        sku: 83874,
        image: "/images/products/product-2.jpg",
        price: 67.62,
        qty: 2,
        discount: 0.38,
        total: 536.59,
        product_id: "PROD-xk9tsqw9",
      },
      {
        name: "Gloves - Goldtouch Disposable",
        sku: 77652,
        image: "/images/products/product-12.jpg",
        price: 514.92,
        qty: 7,
        discount: 0.49,
        total: 244.59,
        product_id: "PROD-viwe0ulu",
      },
      {
        name: "Chinese Lemon Pork",
        sku: 38843,
        image: "/images/products/product-5.jpg",
        price: 267.01,
        qty: 9,
        discount: 0.6,
        total: 160.21,
        product_id: "PROD-enixgo97",
      },
      {
        name: "Towel - Roll White",
        sku: 9655,
        image: "/images/products/product-6.jpg",
        price: 45.55,
        qty: 1,
        discount: 0.08,
        total: 294.06,
        product_id: "PROD-rsbu9n2i",
      },
      {
        name: "Carrots - Jumbo",
        sku: 17843,
        image: "/images/products/product-3.jpg",
        price: 840.44,
        qty: 0,
        discount: 0.26,
        total: 942.41,
        product_id: "PROD-2fhe97op",
      },
      {
        name: "Cheese - Gouda",
        sku: 36918,
        image: "/images/products/product-3.jpg",
        price: 959.06,
        qty: 2,
        discount: 0.11,
        total: 62.5,
        product_id: "PROD-wgwszgoz",
      },
      {
        name: "Milk Powder",
        sku: 96288,
        image: "/images/products/product-9.jpg",
        price: 755.88,
        qty: 8,
        discount: 0.07,
        total: 449.16,
        product_id: "PROD-bfwmdmvv",
      },
    ],
    subtotal: 284.49,
    delivery_fee: 18.91,
    tax: 20,
    total_amount_due: 764.69,
  },
  {
    order_id: "#68586",
    created_at: "1665687053000",
    customer: {
      name: "Karil Canning",
      avatar_img: "/images/avatar/avatar-19.jpg",
      customer_id: "CUST-zjzdbdo2",
    },
    total: 560.62,
    profit: 246.6728,
    payment_status: "paid",
    order_status: "shipping",
    shipping_address: { street: "67251 Sage Crossing", line: "5th Floor" },
    products: [
      {
        name: "Salmon - Whole, 4 - 6 Pounds",
        sku: 58988,
        image: "/images/products/product-7.jpg",
        price: 280.65,
        qty: 1,
        discount: 0.52,
        total: 235.58,
        product_id: "PROD-1wt4rvlu",
      },
      {
        name: "Veal - Shank, Pieces",
        sku: 44640,
        image: "/images/products/product-3.jpg",
        price: 59.77,
        qty: 3,
        discount: 0.45,
        total: 946.77,
        product_id: "PROD-deuqjci5",
      },
      {
        name: "Calypso - Pineapple Passion",
        sku: 27758,
        image: "/images/products/product-11.jpg",
        price: 771.2,
        qty: 6,
        discount: 0.5,
        total: 182.33,
        product_id: "PROD-qbqmcvrb",
      },
      {
        name: "Pie Box - Cello Window 2.5",
        sku: 42045,
        image: "/images/products/product-5.jpg",
        price: 674.85,
        qty: 1,
        discount: 0.48,
        total: 39.91,
        product_id: "PROD-kp6wq6zd",
      },
      {
        name: "Wine - Bourgogne 2002, La",
        sku: 5777,
        image: "/images/products/product-5.jpg",
        price: 958.47,
        qty: 7,
        discount: 0.03,
        total: 138.03,
        product_id: "PROD-jm9sr46z",
      },
      {
        name: "Scrubbie - Scotchbrite Hand Pad",
        sku: 47120,
        image: "/images/products/product-3.jpg",
        price: 733.53,
        qty: 7,
        discount: 0.54,
        total: 633.73,
        product_id: "PROD-r6kmg710",
      },
    ],
    subtotal: 459.9,
    delivery_fee: 53.23,
    tax: 20,
    total_amount_due: 315.22,
  },
  {
    order_id: "#75496",
    created_at: "1668080089000",
    customer: {
      name: "Ruperta Mangenet",
      avatar_img: "/images/avatar/avatar-4.jpg",
      customer_id: "CUST-s9n0iuac",
    },
    total: 109.1,
    profit: 52.368,
    payment_status: "failed",
    order_status: "processing",
    shipping_address: { street: "27 Cottonwood Center", line: "Suite 66" },
    products: [
      {
        name: "Crab - Back Fin Meat, Canned",
        sku: 40362,
        image: "/images/products/product-6.jpg",
        price: 766.02,
        qty: 2,
        discount: 0.48,
        total: 677.56,
        product_id: "PROD-ovfv9x8m",
      },
      {
        name: "Soup - Knorr, Country Bean",
        sku: 64011,
        image: "/images/products/product-4.jpg",
        price: 759.82,
        qty: 4,
        discount: 0.23,
        total: 153.89,
        product_id: "PROD-arfchuvt",
      },
      {
        name: "Cookie Double Choco",
        sku: 56136,
        image: "/images/products/product-5.jpg",
        price: 364.86,
        qty: 8,
        discount: 0.43,
        total: 514.19,
        product_id: "PROD-1nyelk3g",
      },
      {
        name: "Sultanas",
        sku: 71265,
        image: "/images/products/product-7.jpg",
        price: 562.76,
        qty: 8,
        discount: 0.08,
        total: 384.75,
        product_id: "PROD-ntpk1wyh",
      },
      {
        name: "Veal - Bones",
        sku: 33961,
        image: "/images/products/product-4.jpg",
        price: 437.73,
        qty: 4,
        discount: 0.46,
        total: 391.69,
        product_id: "PROD-hqq4edug",
      },
    ],
    subtotal: 443.86,
    delivery_fee: 25.02,
    tax: 20,
    total_amount_due: 838.43,
  },
  {
    order_id: "#47647",
    created_at: "1682391501000",
    customer: {
      name: "Nikki McKendo",
      avatar_img: "/images/avatar/avatar-12.jpg",
      customer_id: "CUST-s4ge3xhk",
    },
    total: 518.27,
    profit: 82.9232,
    payment_status: "paid",
    order_status: "shipping",
    shipping_address: { street: "43 Novick Parkway", line: "Room 905" },
    products: [
      {
        name: "Beef - Bones, Cut - Up",
        sku: 55346,
        image: "/images/products/product-5.jpg",
        price: 346.5,
        qty: 10,
        discount: 0.36,
        total: 418.07,
        product_id: "PROD-8zrp7e3g",
      },
      {
        name: "Swiss Chard",
        sku: 88728,
        image: "/images/products/product-4.jpg",
        price: 776.19,
        qty: 9,
        discount: 0.48,
        total: 867.71,
        product_id: "PROD-jngf1zx6",
      },
      {
        name: "Venison - Striploin",
        sku: 87615,
        image: "/images/products/product-10.jpg",
        price: 386.55,
        qty: 8,
        discount: 0.02,
        total: 888.05,
        product_id: "PROD-tmoqikb7",
      },
      {
        name: "Arizona - Plum Green Tea",
        sku: 93255,
        image: "/images/products/product-3.jpg",
        price: 7.49,
        qty: 2,
        discount: 0.51,
        total: 634.57,
        product_id: "PROD-y1zp7goj",
      },
    ],
    subtotal: 2.96,
    delivery_fee: 34.8,
    tax: 20,
    total_amount_due: 821.98,
  },
  {
    order_id: "#31621",
    created_at: "1675264434000",
    customer: {
      name: "Jaimie Scone",
      avatar_img: "/images/avatar/avatar-15.jpg",
      customer_id: "CUST-77tsinr5",
    },
    total: 349.11,
    profit: 118.6974,
    payment_status: "pending",
    order_status: "pending",
    shipping_address: { street: "22830 Bartillon Crossing", line: "Room 679" },
    products: [
      {
        name: "Cod - Black Whole Fillet",
        sku: 55810,
        image: "/images/products/product-12.jpg",
        price: 686.74,
        qty: 1,
        discount: 0.58,
        total: 443.23,
        product_id: "PROD-l9ufcv16",
      },
      {
        name: "Mushroom - Trumpet, Dry",
        sku: 59025,
        image: "/images/products/product-1.jpg",
        price: 517.8,
        qty: 5,
        discount: 0.11,
        total: 974.21,
        product_id: "PROD-46k6pd9n",
      },
      {
        name: "Sword Pick Asst",
        sku: 32953,
        image: "/images/products/product-8.jpg",
        price: 282.54,
        qty: 7,
        discount: 0.33,
        total: 878.81,
        product_id: "PROD-vhp0f8kd",
      },
      {
        name: "Jameson - Irish Whiskey",
        sku: 66166,
        image: "/images/products/product-5.jpg",
        price: 768.49,
        qty: 0,
        discount: 0.5,
        total: 899.74,
        product_id: "PROD-dkbnrvz6",
      },
      {
        name: "Appetizer - Lobster Phyllo Roll",
        sku: 79506,
        image: "/images/products/product-5.jpg",
        price: 678.25,
        qty: 2,
        discount: 0.19,
        total: 678.18,
        product_id: "PROD-thdqsfej",
      },
      {
        name: "Sprouts Dikon",
        sku: 91961,
        image: "/images/products/product-4.jpg",
        price: 962.86,
        qty: 0,
        discount: 0.5,
        total: 328.7,
        product_id: "PROD-g0pb01lf",
      },
      {
        name: "Seabream Whole Farmed",
        sku: 69600,
        image: "/images/products/product-6.jpg",
        price: 422.66,
        qty: 10,
        discount: 0.06,
        total: 90.73,
        product_id: "PROD-oz7fc449",
      },
    ],
    subtotal: 461.22,
    delivery_fee: 40.69,
    tax: 20,
    total_amount_due: 618.09,
  },
  {
    order_id: "#82775",
    created_at: "1677637599000",
    customer: {
      name: "Mirelle Maccrae",
      avatar_img: null,
      customer_id: "CUST-5a4za3eg",
    },
    total: 700.06,
    profit: 336.0288,
    payment_status: "paid",
    order_status: "pending",
    shipping_address: { street: "861 Forest Run Drive", line: "PO Box 35110" },
    products: [
      {
        name: "Stock - Beef, White",
        sku: 33770,
        image: "/images/products/product-1.jpg",
        price: 132.79,
        qty: 4,
        discount: 0.45,
        total: 885.28,
        product_id: "PROD-3a5u59fk",
      },
      {
        name: "Jameson - Irish Whiskey",
        sku: 29602,
        image: "/images/products/product-4.jpg",
        price: 91.91,
        qty: 7,
        discount: 0.4,
        total: 631.12,
        product_id: "PROD-qgqrafyh",
      },
      {
        name: "Evaporated Milk - Skim",
        sku: 13982,
        image: "/images/products/product-4.jpg",
        price: 527.87,
        qty: 6,
        discount: 0.23,
        total: 583.7,
        product_id: "PROD-scj67h51",
      },
      {
        name: "Glass Clear 7 Oz Xl",
        sku: 85175,
        image: "/images/products/product-9.jpg",
        price: 642.05,
        qty: 3,
        discount: 0.25,
        total: 901.2,
        product_id: "PROD-ldvp0sv9",
      },
      {
        name: "Salmon - Atlantic, Fresh, Whole",
        sku: 83644,
        image: "/images/products/product-12.jpg",
        price: 851.98,
        qty: 1,
        discount: 0.55,
        total: 951.3,
        product_id: "PROD-y80nbk7y",
      },
      {
        name: "Plate - Foam, Bread And Butter",
        sku: 53968,
        image: "/images/products/product-9.jpg",
        price: 607.67,
        qty: 0,
        discount: 0.46,
        total: 992.56,
        product_id: "PROD-ycka7u1k",
      },
      {
        name: "Pasta - Fusili Tri - Coloured",
        sku: 43813,
        image: "/images/products/product-4.jpg",
        price: 124.14,
        qty: 9,
        discount: 0.57,
        total: 285.48,
        product_id: "PROD-wb30eppy",
      },
      {
        name: "Wine - Tio Pepe Sherry Fino",
        sku: 2429,
        image: "/images/products/product-2.jpg",
        price: 40.3,
        qty: 10,
        discount: 0.29,
        total: 943.79,
        product_id: "PROD-8x6ykgrg",
      },
      {
        name: "Icecream - Dstk Cml And Fdg",
        sku: 59935,
        image: "/images/products/product-12.jpg",
        price: 447.11,
        qty: 2,
        discount: 0.45,
        total: 307.33,
        product_id: "PROD-sedv33c1",
      },
    ],
    subtotal: 250.44,
    delivery_fee: 90.66,
    tax: 20,
    total_amount_due: 583.2,
  },
  {
    order_id: "#24195",
    created_at: "1670426379000",
    customer: {
      name: "Sloane Whybray",
      avatar_img: "/images/avatar/avatar-9.jpg",
      customer_id: "CUST-lwsw6ly7",
    },
    total: 633.86,
    profit: 342.2844,
    payment_status: "pending",
    order_status: "shipping",
    shipping_address: { street: "21319 Crowley Plaza", line: "Room 502" },
    products: [
      {
        name: "Cod - Fillets",
        sku: 54881,
        image: "/images/products/product-1.jpg",
        price: 459.14,
        qty: 9,
        discount: 0.53,
        total: 260.28,
        product_id: "PROD-zwfiygs2",
      },
      {
        name: "Shrimp - Tiger 21/25",
        sku: 43857,
        image: "/images/products/product-1.jpg",
        price: 552.56,
        qty: 1,
        discount: 0.07,
        total: 739.52,
        product_id: "PROD-y2c4mzf3",
      },
      {
        name: "Dried Cranberries",
        sku: 92642,
        image: "/images/products/product-1.jpg",
        price: 504.75,
        qty: 10,
        discount: 0.05,
        total: 25.42,
        product_id: "PROD-zo21nkpl",
      },
      {
        name: "Aspic - Light",
        sku: 87892,
        image: "/images/products/product-9.jpg",
        price: 621.25,
        qty: 10,
        discount: 0.53,
        total: 10.59,
        product_id: "PROD-8tot024j",
      },
    ],
    subtotal: 452.9,
    delivery_fee: 79.18,
    tax: 20,
    total_amount_due: 23.42,
  },
  {
    order_id: "#15559",
    created_at: "1655416800000",
    customer: {
      name: "Randi Levey",
      avatar_img: null,
      customer_id: "CUST-7ltllggk",
    },
    total: 140.88,
    profit: 69.0312,
    payment_status: "failed",
    order_status: "cancelled",
    shipping_address: { street: "131 Bowman Crossing", line: "PO Box 81166" },
    products: [
      {
        name: "Wine - Baron De Rothschild",
        sku: 46782,
        image: "/images/products/product-4.jpg",
        price: 660.82,
        qty: 7,
        discount: 0.14,
        total: 288.67,
        product_id: "PROD-5ullz877",
      },
      {
        name: "Pastry - Lemon Danish - Mini",
        sku: 65087,
        image: "/images/products/product-1.jpg",
        price: 922.15,
        qty: 9,
        discount: 0.58,
        total: 563.84,
        product_id: "PROD-w21ay913",
      },
      {
        name: "Appetizer - Smoked Salmon / Dill",
        sku: 4724,
        image: "/images/products/product-5.jpg",
        price: 779.97,
        qty: 9,
        discount: 0.08,
        total: 351.33,
        product_id: "PROD-zvqexe6y",
      },
    ],
    subtotal: 53.37,
    delivery_fee: 40.28,
    tax: 20,
    total_amount_due: 336.81,
  },
  {
    order_id: "#57021",
    created_at: "1655434171000",
    customer: {
      name: "Augustus Akess",
      avatar_img: "/images/avatar/avatar-18.jpg",
      customer_id: "CUST-jbam3juc",
    },
    total: 217.17,
    profit: 47.7774,
    payment_status: "failed",
    order_status: "cancelled",
    shipping_address: { street: "12 Starling Point", line: "Room 1201" },
    products: [
      {
        name: "Pepper - Pablano",
        sku: 25789,
        image: "/images/products/product-4.jpg",
        price: 211.7,
        qty: 4,
        discount: 0.08,
        total: 174.77,
        product_id: "PROD-ew8va4ui",
      },
      {
        name: "Spinach - Packaged",
        sku: 64,
        image: "/images/products/product-12.jpg",
        price: 839.85,
        qty: 8,
        discount: 0.36,
        total: 813.33,
        product_id: "PROD-g2jsx9ma",
      },
      {
        name: "Tart Shells - Sweet, 4",
        sku: 76279,
        image: "/images/products/product-1.jpg",
        price: 991.74,
        qty: 0,
        discount: 0.11,
        total: 419.75,
        product_id: "PROD-4eqrqvom",
      },
      {
        name: "Bok Choy - Baby",
        sku: 89656,
        image: "/images/products/product-5.jpg",
        price: 489.95,
        qty: 3,
        discount: 0.14,
        total: 290.63,
        product_id: "PROD-d3g89raq",
      },
      {
        name: "Goulash Seasoning",
        sku: 42719,
        image: "/images/products/product-11.jpg",
        price: 987.11,
        qty: 2,
        discount: 0.36,
        total: 617.2,
        product_id: "PROD-fjqezxap",
      },
      {
        name: "Plaintain",
        sku: 8826,
        image: "/images/products/product-4.jpg",
        price: 490.5,
        qty: 10,
        discount: 0.07,
        total: 349.07,
        product_id: "PROD-v9mlsmfr",
      },
      {
        name: "Shrimp - Baby, Warm Water",
        sku: 17668,
        image: "/images/products/product-6.jpg",
        price: 924.46,
        qty: 3,
        discount: 0.49,
        total: 556.77,
        product_id: "PROD-7b9sqj7v",
      },
    ],
    subtotal: 484.93,
    delivery_fee: 57.84,
    tax: 20,
    total_amount_due: 831.29,
  },
  {
    order_id: "#78585",
    created_at: "1681845527000",
    customer: {
      name: "Elwin Averill",
      avatar_img: "/images/avatar/avatar-13.jpg",
      customer_id: "CUST-a9573fmk",
    },
    total: 841.22,
    profit: 92.5342,
    payment_status: "failed",
    order_status: "pending",
    shipping_address: { street: "6 Crowley Drive", line: "Room 1946" },
    products: [
      {
        name: "Barramundi",
        sku: 56574,
        image: "/images/products/product-3.jpg",
        price: 619.88,
        qty: 0,
        discount: 0.07,
        total: 427.82,
        product_id: "PROD-sk286boz",
      },
      {
        name: "Beef - Bresaola",
        sku: 42228,
        image: "/images/products/product-12.jpg",
        price: 244.59,
        qty: 5,
        discount: 0.47,
        total: 350.59,
        product_id: "PROD-td84q3uw",
      },
      {
        name: "Chervil - Fresh",
        sku: 25507,
        image: "/images/products/product-6.jpg",
        price: 100.11,
        qty: 7,
        discount: 0.51,
        total: 724.96,
        product_id: "PROD-o9hwib4x",
      },
      {
        name: "Olives - Nicoise",
        sku: 31309,
        image: "/images/products/product-10.jpg",
        price: 172.07,
        qty: 2,
        discount: 0.3,
        total: 802.12,
        product_id: "PROD-0p4sbz0e",
      },
      {
        name: "Pasta - Lasagne, Fresh",
        sku: 24771,
        image: "/images/products/product-5.jpg",
        price: 107.11,
        qty: 7,
        discount: 0.55,
        total: 553.35,
        product_id: "PROD-xz2fkzjz",
      },
      {
        name: "Salmon - Atlantic, No Skin",
        sku: 13276,
        image: "/images/products/product-2.jpg",
        price: 901.06,
        qty: 2,
        discount: 0.4,
        total: 315.82,
        product_id: "PROD-vx338zrj",
      },
      {
        name: "Salsify, Organic",
        sku: 86943,
        image: "/images/products/product-12.jpg",
        price: 466.57,
        qty: 6,
        discount: 0.49,
        total: 690.97,
        product_id: "PROD-ow1w3o33",
      },
      {
        name: "Bagels Poppyseed",
        sku: 18998,
        image: "/images/products/product-2.jpg",
        price: 345.67,
        qty: 0,
        discount: 0.18,
        total: 797.41,
        product_id: "PROD-i46hc3qb",
      },
      {
        name: "Muffin Mix - Blueberry",
        sku: 1174,
        image: "/images/products/product-10.jpg",
        price: 820.91,
        qty: 3,
        discount: 0.57,
        total: 47.79,
        product_id: "PROD-ji80m2ef",
      },
    ],
    subtotal: 645.24,
    delivery_fee: 10.96,
    tax: 20,
    total_amount_due: 763.59,
  },
  {
    order_id: "#43607",
    created_at: "1662337403000",
    customer: {
      name: "Stan Keaves",
      avatar_img: null,
      customer_id: "CUST-sb4t4g09",
    },
    total: 532.14,
    profit: 85.1424,
    payment_status: "failed",
    order_status: "shipping",
    shipping_address: { street: "3 Division Junction", line: "Suite 64" },
    products: [
      {
        name: "Sambuca Cream",
        sku: 35562,
        image: "/images/products/product-1.jpg",
        price: 829.1,
        qty: 8,
        discount: 0.49,
        total: 887.06,
        product_id: "PROD-80ymf8hx",
      },
      {
        name: "Blue Curacao - Marie Brizard",
        sku: 72572,
        image: "/images/products/product-3.jpg",
        price: 322.96,
        qty: 3,
        discount: 0.13,
        total: 510.81,
        product_id: "PROD-w8o6d8ie",
      },
      {
        name: "Scallops 60/80 Iqf",
        sku: 76855,
        image: "/images/products/product-2.jpg",
        price: 327.66,
        qty: 5,
        discount: 0.19,
        total: 232.93,
        product_id: "PROD-7sa7xq9d",
      },
      {
        name: "Fish - Atlantic Salmon, Cold",
        sku: 28492,
        image: "/images/products/product-6.jpg",
        price: 939.32,
        qty: 8,
        discount: 0.21,
        total: 953.52,
        product_id: "PROD-2q58e9lq",
      },
    ],
    subtotal: 737.08,
    delivery_fee: 24.09,
    tax: 20,
    total_amount_due: 455.99,
  },
  {
    order_id: "#50303",
    created_at: "1672797045000",
    customer: {
      name: "Kameko Basant",
      avatar_img: "/images/avatar/avatar-11.jpg",
      customer_id: "CUST-5x3ednio",
    },
    total: 682.57,
    profit: 218.4224,
    payment_status: "failed",
    order_status: "processing",
    shipping_address: { street: "535 West Circle", line: "PO Box 89682" },
    products: [
      {
        name: "Catfish - Fillets",
        sku: 18601,
        image: "/images/products/product-2.jpg",
        price: 234.1,
        qty: 3,
        discount: 0.12,
        total: 236.55,
        product_id: "PROD-d5tdmmhe",
      },
      {
        name: "Wine - Ruffino Chianti",
        sku: 29206,
        image: "/images/products/product-8.jpg",
        price: 328.34,
        qty: 3,
        discount: 0.29,
        total: 786.3,
        product_id: "PROD-l7h5nz8q",
      },
      {
        name: "Flavouring - Orange",
        sku: 46700,
        image: "/images/products/product-11.jpg",
        price: 460.68,
        qty: 6,
        discount: 0.41,
        total: 981.31,
        product_id: "PROD-sfoe1qyg",
      },
      {
        name: "Hot Chocolate - Individual",
        sku: 65434,
        image: "/images/products/product-3.jpg",
        price: 948.2,
        qty: 3,
        discount: 0.38,
        total: 607.81,
        product_id: "PROD-lave0mwt",
      },
      {
        name: "Juice - Clam, 46 Oz",
        sku: 66347,
        image: "/images/products/product-7.jpg",
        price: 734.89,
        qty: 2,
        discount: 0.3,
        total: 340.55,
        product_id: "PROD-8t8th8o3",
      },
      {
        name: "Onions - Cippolini",
        sku: 40259,
        image: "/images/products/product-5.jpg",
        price: 346.12,
        qty: 8,
        discount: 0.11,
        total: 698.41,
        product_id: "PROD-2wxaqni5",
      },
      {
        name: "Instant Coffee",
        sku: 72127,
        image: "/images/products/product-2.jpg",
        price: 857.98,
        qty: 5,
        discount: 0.48,
        total: 594.58,
        product_id: "PROD-5tapm3lz",
      },
    ],
    subtotal: 714.58,
    delivery_fee: 49.03,
    tax: 20,
    total_amount_due: 732.16,
  },
  {
    order_id: "#18287",
    created_at: "1657281679000",
    customer: {
      name: "Sheba Boldison",
      avatar_img: "/images/avatar/avatar-14.jpg",
      customer_id: "CUST-jf4gqlnf",
    },
    total: 29.43,
    profit: 6.7689,
    payment_status: "paid",
    order_status: "pending",
    shipping_address: { street: "2844 Bowman Alley", line: "Suite 82" },
    products: [
      {
        name: "Bread Bowl Plain",
        sku: 27695,
        image: "/images/products/product-6.jpg",
        price: 331.93,
        qty: 9,
        discount: 0.08,
        total: 587.07,
        product_id: "PROD-pc1curfh",
      },
      {
        name: "Creme De Cacao Mcguines",
        sku: 92259,
        image: "/images/products/product-4.jpg",
        price: 173.49,
        qty: 5,
        discount: 0.04,
        total: 397.25,
        product_id: "PROD-zab4e25u",
      },
      {
        name: "Bread - Bagels, Mini",
        sku: 91368,
        image: "/images/products/product-6.jpg",
        price: 287.58,
        qty: 5,
        discount: 0.41,
        total: 879.13,
        product_id: "PROD-gmmag9o6",
      },
      {
        name: "Pasta - Shells, Medium, Dry",
        sku: 19319,
        image: "/images/products/product-11.jpg",
        price: 506.78,
        qty: 10,
        discount: 0.35,
        total: 730.58,
        product_id: "PROD-i6num3e2",
      },
      {
        name: "Cabbage - Savoy",
        sku: 46131,
        image: "/images/products/product-8.jpg",
        price: 313.15,
        qty: 9,
        discount: 0.01,
        total: 889.13,
        product_id: "PROD-nnbsfocn",
      },
      {
        name: "Cassis",
        sku: 32198,
        image: "/images/products/product-9.jpg",
        price: 295.27,
        qty: 5,
        discount: 0.15,
        total: 71.05,
        product_id: "PROD-5b1z5o0m",
      },
      {
        name: "Soup - French Can Pea",
        sku: 23609,
        image: "/images/products/product-9.jpg",
        price: 24.91,
        qty: 6,
        discount: 0.3,
        total: 125.17,
        product_id: "PROD-gfu889zq",
      },
      {
        name: "Pepper - White, Ground",
        sku: 17584,
        image: "/images/products/product-3.jpg",
        price: 969.28,
        qty: 3,
        discount: 0.38,
        total: 930.1,
        product_id: "PROD-qtkr875h",
      },
      {
        name: "The Pop Shoppe - Black Cherry",
        sku: 64488,
        image: "/images/products/product-7.jpg",
        price: 825.7,
        qty: 9,
        discount: 0.17,
        total: 595.8,
        product_id: "PROD-hbxve8u4",
      },
      {
        name: "Cheese - Wine",
        sku: 25875,
        image: "/images/products/product-11.jpg",
        price: 606.5,
        qty: 9,
        discount: 0.38,
        total: 120.41,
        product_id: "PROD-7l8xqchb",
      },
    ],
    subtotal: 590.52,
    delivery_fee: 17.67,
    tax: 20,
    total_amount_due: 280.56,
  },
  {
    order_id: "#57144",
    created_at: "1665007756000",
    customer: {
      name: "Rosy Roeby",
      avatar_img: "/images/avatar/avatar-13.jpg",
      customer_id: "CUST-dr0t0dtr",
    },
    total: 833.18,
    profit: 149.9724,
    payment_status: "pending",
    order_status: "shipping",
    shipping_address: { street: "462 Artisan Point", line: "PO Box 40552" },
    products: [
      {
        name: "Beer - Guiness",
        sku: 51480,
        image: "/images/products/product-12.jpg",
        price: 489.78,
        qty: 10,
        discount: 0.54,
        total: 526.98,
        product_id: "PROD-ujamdl6u",
      },
      {
        name: "Cookie - Oatmeal",
        sku: 8174,
        image: "/images/products/product-11.jpg",
        price: 745.23,
        qty: 3,
        discount: 0.51,
        total: 38.28,
        product_id: "PROD-ytfnkif6",
      },
    ],
    subtotal: 111.2,
    delivery_fee: 91.2,
    tax: 20,
    total_amount_due: 196.19,
  },
  {
    order_id: "#12447",
    created_at: "1673719759000",
    customer: {
      name: "Baillie Normanton",
      avatar_img: "/images/avatar/avatar-12.jpg",
      customer_id: "CUST-jbficle2",
    },
    total: 471.14,
    profit: 230.8586,
    payment_status: "pending",
    order_status: "pending",
    shipping_address: { street: "22167 Continental Pass", line: "16th Floor" },
    products: [
      {
        name: "Bonito Flakes - Toku Katsuo",
        sku: 58919,
        image: "/images/products/product-3.jpg",
        price: 588.71,
        qty: 4,
        discount: 0.22,
        total: 954.87,
        product_id: "PROD-4ew3lkyr",
      },
      {
        name: "Parsley - Fresh",
        sku: 8880,
        image: "/images/products/product-4.jpg",
        price: 952.83,
        qty: 1,
        discount: 0.39,
        total: 660.3,
        product_id: "PROD-oiyj7rc3",
      },
      {
        name: "Coffee Decaf Colombian",
        sku: 91610,
        image: "/images/products/product-6.jpg",
        price: 65.47,
        qty: 3,
        discount: 0.39,
        total: 971.49,
        product_id: "PROD-va15p99h",
      },
      {
        name: "Carbonated Water - Orange",
        sku: 65236,
        image: "/images/products/product-6.jpg",
        price: 678.36,
        qty: 7,
        discount: 0.33,
        total: 716.68,
        product_id: "PROD-8esvptsc",
      },
    ],
    subtotal: 133.14,
    delivery_fee: 81.19,
    tax: 20,
    total_amount_due: 962.11,
  },
  {
    order_id: "#43898",
    created_at: "1673782496000",
    customer: {
      name: "Gwendolyn Camier",
      avatar_img: "/images/avatar/avatar-14.jpg",
      customer_id: "CUST-ibzb7vj9",
    },
    total: 609.31,
    profit: 292.4688,
    payment_status: "pending",
    order_status: "cancelled",
    shipping_address: { street: "984 Weeping Birch Trail", line: "Apt 984" },
    products: [
      {
        name: "Quiche Assorted",
        sku: 53822,
        image: "/images/products/product-4.jpg",
        price: 67.96,
        qty: 9,
        discount: 0.01,
        total: 236.9,
        product_id: "PROD-sjowy630",
      },
      {
        name: "Cherries - Frozen",
        sku: 6094,
        image: "/images/products/product-6.jpg",
        price: 163.06,
        qty: 4,
        discount: 0.54,
        total: 458.7,
        product_id: "PROD-7ovwhcjm",
      },
      {
        name: "Cakes Assorted",
        sku: 62733,
        image: "/images/products/product-8.jpg",
        price: 212.32,
        qty: 1,
        discount: 0.33,
        total: 73.52,
        product_id: "PROD-qk6l5mai",
      },
      {
        name: "Bay Leaf Ground",
        sku: 83776,
        image: "/images/products/product-1.jpg",
        price: 646.04,
        qty: 4,
        discount: 0.32,
        total: 108.19,
        product_id: "PROD-thzytrg4",
      },
      {
        name: "Nantucket Pine Orangebanana",
        sku: 40307,
        image: "/images/products/product-12.jpg",
        price: 51.76,
        qty: 6,
        discount: 0.09,
        total: 294.88,
        product_id: "PROD-ugmw2b5d",
      },
      {
        name: "Rootbeer",
        sku: 68972,
        image: "/images/products/product-11.jpg",
        price: 353.47,
        qty: 2,
        discount: 0.51,
        total: 426.26,
        product_id: "PROD-8d9wpeuz",
      },
      {
        name: "Cheese - Le Cru Du Clocher",
        sku: 44360,
        image: "/images/products/product-10.jpg",
        price: 282.7,
        qty: 3,
        discount: 0.2,
        total: 877.81,
        product_id: "PROD-54vfyxwa",
      },
      {
        name: "Bag Stand",
        sku: 8339,
        image: "/images/products/product-10.jpg",
        price: 861.17,
        qty: 2,
        discount: 0.29,
        total: 360.17,
        product_id: "PROD-ujctdhz6",
      },
      {
        name: "Bread - Rolls, Corn",
        sku: 22087,
        image: "/images/products/product-10.jpg",
        price: 918.23,
        qty: 10,
        discount: 0.4,
        total: 395.5,
        product_id: "PROD-14pul2zk",
      },
      {
        name: "Veal - Inside Round / Top, Lean",
        sku: 92985,
        image: "/images/products/product-11.jpg",
        price: 401.07,
        qty: 10,
        discount: 0.56,
        total: 480.9,
        product_id: "PROD-fh6zxlt2",
      },
    ],
    subtotal: 537.14,
    delivery_fee: 50.45,
    tax: 20,
    total_amount_due: 272.26,
  },
  {
    order_id: "#16888",
    created_at: "1675787440000",
    customer: {
      name: "Sidonnie Popley",
      avatar_img: "/images/avatar/avatar-19.jpg",
      customer_id: "CUST-lt6fxjh1",
    },
    total: 335.66,
    profit: 167.83,
    payment_status: "pending",
    order_status: "shipping",
    shipping_address: { street: "7087 Monica Plaza", line: "Apt 939" },
    products: [
      {
        name: "Ham Black Forest",
        sku: 120,
        image: "/images/products/product-8.jpg",
        price: 643.84,
        qty: 0,
        discount: 0.09,
        total: 621.72,
        product_id: "PROD-erhbzrqg",
      },
      {
        name: "Liqueur Banana, Ramazzotti",
        sku: 75346,
        image: "/images/products/product-6.jpg",
        price: 184.26,
        qty: 10,
        discount: 0.54,
        total: 711.07,
        product_id: "PROD-e8wmbkon",
      },
      {
        name: "Pork - Smoked Kassler",
        sku: 87399,
        image: "/images/products/product-7.jpg",
        price: 835.04,
        qty: 9,
        discount: 0.53,
        total: 399.89,
        product_id: "PROD-ott38wda",
      },
      {
        name: "Mushroom - King Eryingii",
        sku: 53039,
        image: "/images/products/product-5.jpg",
        price: 897.81,
        qty: 2,
        discount: 0.4,
        total: 482.83,
        product_id: "PROD-pelv6x7h",
      },
      {
        name: "Potato - Sweet",
        sku: 62690,
        image: "/images/products/product-1.jpg",
        price: 786.34,
        qty: 10,
        discount: 0.29,
        total: 897.83,
        product_id: "PROD-cjz12kfo",
      },
      {
        name: "Wine - Harrow Estates, Vidal",
        sku: 18714,
        image: "/images/products/product-5.jpg",
        price: 546.53,
        qty: 9,
        discount: 0.24,
        total: 761.35,
        product_id: "PROD-ohzo37vc",
      },
    ],
    subtotal: 449.83,
    delivery_fee: 92.15,
    tax: 20,
    total_amount_due: 862.46,
  },
  {
    order_id: "#82847",
    created_at: "1662505323000",
    customer: {
      name: "Carla Stannion",
      avatar_img: "/images/avatar/avatar-15.jpg",
      customer_id: "CUST-jbzkmc21",
    },
    total: 514.92,
    profit: 72.0888,
    payment_status: "pending",
    order_status: "cancelled",
    shipping_address: { street: "8 Mandrake Center", line: "Suite 40" },
    products: [
      {
        name: "Beer - Corona",
        sku: 77723,
        image: "/images/products/product-11.jpg",
        price: 182.0,
        qty: 0,
        discount: 0.04,
        total: 969.14,
        product_id: "PROD-ywskikm3",
      },
      {
        name: "Tarragon - Fresh",
        sku: 91188,
        image: "/images/products/product-1.jpg",
        price: 573.13,
        qty: 1,
        discount: 0.33,
        total: 801.72,
        product_id: "PROD-1j88vkxj",
      },
      {
        name: "Tarts Assorted",
        sku: 26806,
        image: "/images/products/product-6.jpg",
        price: 457.27,
        qty: 4,
        discount: 0.31,
        total: 6.14,
        product_id: "PROD-db90655v",
      },
      {
        name: "Sprouts - Bean",
        sku: 71663,
        image: "/images/products/product-10.jpg",
        price: 164.53,
        qty: 5,
        discount: 0.15,
        total: 986.73,
        product_id: "PROD-y5vbo41o",
      },
    ],
    subtotal: 787.22,
    delivery_fee: 65.02,
    tax: 20,
    total_amount_due: 891.98,
  },
  {
    order_id: "#78323",
    created_at: "1670964637000",
    customer: {
      name: "Wesley Niesel",
      avatar_img: null,
      customer_id: "CUST-tj448ue2",
    },
    total: 433.71,
    profit: 182.1582,
    payment_status: "paid",
    order_status: "cancelled",
    shipping_address: { street: "301 Steensland Center", line: "14th Floor" },
    products: [
      {
        name: "Octopus - Baby, Cleaned",
        sku: 84969,
        image: "/images/products/product-10.jpg",
        price: 722.74,
        qty: 2,
        discount: 0.4,
        total: 19.31,
        product_id: "PROD-p2yvoe8u",
      },
      {
        name: "Muffin Mix - Chocolate Chip",
        sku: 10435,
        image: "/images/products/product-8.jpg",
        price: 904.74,
        qty: 2,
        discount: 0.49,
        total: 519.4,
        product_id: "PROD-wxnu10tl",
      },
      {
        name: "Ham - Black Forest",
        sku: 17394,
        image: "/images/products/product-10.jpg",
        price: 320.44,
        qty: 1,
        discount: 0.02,
        total: 259.01,
        product_id: "PROD-4a71qveb",
      },
      {
        name: "Onions - White",
        sku: 97763,
        image: "/images/products/product-11.jpg",
        price: 26.02,
        qty: 4,
        discount: 0.25,
        total: 643.89,
        product_id: "PROD-3gqqf2sp",
      },
      {
        name: "Anisette - Mcguiness",
        sku: 79802,
        image: "/images/products/product-9.jpg",
        price: 795.56,
        qty: 10,
        discount: 0.23,
        total: 933.11,
        product_id: "PROD-tx0tuiti",
      },
      {
        name: "Artichoke - Fresh",
        sku: 66167,
        image: "/images/products/product-12.jpg",
        price: 245.98,
        qty: 8,
        discount: 0.41,
        total: 691.13,
        product_id: "PROD-8zjv7pi8",
      },
      {
        name: "Chocolate - Chips Compound",
        sku: 52854,
        image: "/images/products/product-3.jpg",
        price: 749.03,
        qty: 10,
        discount: 0.21,
        total: 976.0,
        product_id: "PROD-xffb9vel",
      },
      {
        name: "Honey - Liquid",
        sku: 10168,
        image: "/images/products/product-11.jpg",
        price: 300.88,
        qty: 10,
        discount: 0.04,
        total: 990.43,
        product_id: "PROD-bknxoeul",
      },
      {
        name: "Coffee Cup 12oz 5342cd",
        sku: 71731,
        image: "/images/products/product-7.jpg",
        price: 292.8,
        qty: 5,
        discount: 0.32,
        total: 649.85,
        product_id: "PROD-nn1ypn7u",
      },
    ],
    subtotal: 559.63,
    delivery_fee: 88.5,
    tax: 20,
    total_amount_due: 485.91,
  },
  {
    order_id: "#95726",
    created_at: "1651497345000",
    customer: {
      name: "Brandy Castagnet",
      avatar_img: null,
      customer_id: "CUST-v6xi7t9n",
    },
    total: 70.57,
    profit: 29.6394,
    payment_status: "pending",
    order_status: "processing",
    shipping_address: { street: "62310 Loeprich Center", line: "19th Floor" },
    products: [
      {
        name: "Orange - Tangerine",
        sku: 21744,
        image: "/images/products/product-11.jpg",
        price: 752.46,
        qty: 8,
        discount: 0.06,
        total: 952.08,
        product_id: "PROD-jg7mkeap",
      },
      {
        name: "Cake Sheet Combo Party Pack",
        sku: 1072,
        image: "/images/products/product-8.jpg",
        price: 327.14,
        qty: 0,
        discount: 0.09,
        total: 936.92,
        product_id: "PROD-nwe88vrp",
      },
      {
        name: "Coffee Cup 12oz 5342cd",
        sku: 35166,
        image: "/images/products/product-11.jpg",
        price: 442.71,
        qty: 10,
        discount: 0.43,
        total: 717.42,
        product_id: "PROD-czuozkp1",
      },
    ],
    subtotal: 285.34,
    delivery_fee: 62.74,
    tax: 20,
    total_amount_due: 674.8,
  },
  {
    order_id: "#81501",
    created_at: "1657999046000",
    customer: {
      name: "Patric Blois",
      avatar_img: "/images/avatar/avatar-14.jpg",
      customer_id: "CUST-jo3fq1v0",
    },
    total: 613.66,
    profit: 245.464,
    payment_status: "pending",
    order_status: "pending",
    shipping_address: { street: "5 Cardinal Parkway", line: "PO Box 34397" },
    products: [
      {
        name: "Chick Peas - Dried",
        sku: 93074,
        image: "/images/products/product-6.jpg",
        price: 550.45,
        qty: 10,
        discount: 0.12,
        total: 161.11,
        product_id: "PROD-cdckpbqx",
      },
      {
        name: "Cake - Cake Sheet Macaroon",
        sku: 97390,
        image: "/images/products/product-12.jpg",
        price: 642.0,
        qty: 2,
        discount: 0.27,
        total: 91.28,
        product_id: "PROD-quxaqfn1",
      },
      {
        name: "Crackers - Trio",
        sku: 9206,
        image: "/images/products/product-12.jpg",
        price: 230.93,
        qty: 0,
        discount: 0.44,
        total: 21.7,
        product_id: "PROD-gdc2aa7x",
      },
    ],
    subtotal: 724.67,
    delivery_fee: 79.18,
    tax: 20,
    total_amount_due: 159.89,
  },
  {
    order_id: "#68558",
    created_at: "1662960009000",
    customer: {
      name: "Tiebout Craze",
      avatar_img: "/images/avatar/avatar-12.jpg",
      customer_id: "CUST-weykk1wn",
    },
    total: 974.01,
    profit: 477.2649,
    payment_status: "failed",
    order_status: "processing",
    shipping_address: { street: "29164 Loomis Place", line: "Apt 468" },
    products: [
      {
        name: "Soup - Base Broth Chix",
        sku: 36473,
        image: "/images/products/product-8.jpg",
        price: 64.07,
        qty: 5,
        discount: 0.4,
        total: 793.92,
        product_id: "PROD-mkijxm2s",
      },
    ],
    subtotal: 687.74,
    delivery_fee: 79.86,
    tax: 20,
    total_amount_due: 643.73,
  },
  {
    order_id: "#98004",
    created_at: "1651201647000",
    customer: {
      name: "Ambrosius Alforde",
      avatar_img: "/images/avatar/avatar-18.jpg",
      customer_id: "CUST-aqzhgvt1",
    },
    total: 311.21,
    profit: 180.5018,
    payment_status: "pending",
    order_status: "shipping",
    shipping_address: { street: "9273 Bonner Road", line: "PO Box 73051" },
    products: [
      {
        name: "Potatoes - Yukon Gold, 80 Ct",
        sku: 58721,
        image: "/images/products/product-6.jpg",
        price: 660.54,
        qty: 3,
        discount: 0.01,
        total: 581.15,
        product_id: "PROD-vhc0suqy",
      },
      {
        name: "Tray - Foam, Square 4 - S",
        sku: 39130,
        image: "/images/products/product-12.jpg",
        price: 838.84,
        qty: 9,
        discount: 0.43,
        total: 716.89,
        product_id: "PROD-afuroofy",
      },
      {
        name: "Strawberries",
        sku: 38660,
        image: "/images/products/product-8.jpg",
        price: 932.89,
        qty: 5,
        discount: 0.32,
        total: 425.7,
        product_id: "PROD-95ftomxl",
      },
      {
        name: "Beans - Kidney White",
        sku: 17120,
        image: "/images/products/product-12.jpg",
        price: 805.11,
        qty: 2,
        discount: 0.35,
        total: 58.4,
        product_id: "PROD-2rdng323",
      },
      {
        name: "Compound - Passion Fruit",
        sku: 11029,
        image: "/images/products/product-12.jpg",
        price: 978.1,
        qty: 5,
        discount: 0.57,
        total: 455.41,
        product_id: "PROD-5rcosneq",
      },
    ],
    subtotal: 82.72,
    delivery_fee: 47.78,
    tax: 20,
    total_amount_due: 389.46,
  },
  {
    order_id: "#69816",
    created_at: "1680941932000",
    customer: {
      name: "Candide Crosgrove",
      avatar_img: null,
      customer_id: "CUST-0dpjxwcs",
    },
    total: 452.1,
    profit: 58.773,
    payment_status: "pending",
    order_status: "shipping",
    shipping_address: {
      street: "98957 Glacier Hill Avenue",
      line: "14th Floor",
    },
    products: [
      {
        name: "Baking Soda",
        sku: 61388,
        image: "/images/products/product-11.jpg",
        price: 851.04,
        qty: 7,
        discount: 0.03,
        total: 710.84,
        product_id: "PROD-8oajnk2d",
      },
      {
        name: "Lettuce - Iceberg",
        sku: 5730,
        image: "/images/products/product-6.jpg",
        price: 844.01,
        qty: 9,
        discount: 0.21,
        total: 287.47,
        product_id: "PROD-2nf8lf1l",
      },
      {
        name: "Milkettes - 2%",
        sku: 52247,
        image: "/images/products/product-11.jpg",
        price: 514.7,
        qty: 8,
        discount: 0.55,
        total: 175.61,
        product_id: "PROD-ztrix7sx",
      },
      {
        name: "Broom - Push",
        sku: 33124,
        image: "/images/products/product-10.jpg",
        price: 810.14,
        qty: 7,
        discount: 0.42,
        total: 3.07,
        product_id: "PROD-l23g7v8n",
      },
      {
        name: "Sparkling Wine - Rose, Freixenet",
        sku: 96090,
        image: "/images/products/product-3.jpg",
        price: 412.29,
        qty: 10,
        discount: 0.15,
        total: 190.87,
        product_id: "PROD-n2vo6cox",
      },
    ],
    subtotal: 124.84,
    delivery_fee: 86.42,
    tax: 20,
    total_amount_due: 918.38,
  },
  {
    order_id: "#48168",
    created_at: "1660923297000",
    customer: {
      name: "Haze Karolowski",
      avatar_img: "/images/avatar/avatar-20.jpg",
      customer_id: "CUST-jtvb5wok",
    },
    total: 644.17,
    profit: 173.9259,
    payment_status: "paid",
    order_status: "cancelled",
    shipping_address: { street: "48845 Hooker Street", line: "Room 115" },
    products: [
      {
        name: "Clams - Canned",
        sku: 44947,
        image: "/images/products/product-3.jpg",
        price: 981.42,
        qty: 10,
        discount: 0.01,
        total: 627.78,
        product_id: "PROD-wgkfh46z",
      },
      {
        name: "Danishes - Mini Cheese",
        sku: 62783,
        image: "/images/products/product-6.jpg",
        price: 981.51,
        qty: 8,
        discount: 0.06,
        total: 482.9,
        product_id: "PROD-chwyp7kg",
      },
      {
        name: "Sobe - Berry Energy",
        sku: 86801,
        image: "/images/products/product-12.jpg",
        price: 709.4,
        qty: 10,
        discount: 0.14,
        total: 862.17,
        product_id: "PROD-baidgx51",
      },
      {
        name: "Yogurt - Raspberry, 175 Gr",
        sku: 86418,
        image: "/images/products/product-2.jpg",
        price: 91.21,
        qty: 9,
        discount: 0.32,
        total: 16.74,
        product_id: "PROD-h8c8ux8g",
      },
      {
        name: "Red Currants",
        sku: 99171,
        image: "/images/products/product-11.jpg",
        price: 678.75,
        qty: 10,
        discount: 0.28,
        total: 416.49,
        product_id: "PROD-sey7zc67",
      },
      {
        name: "Hot Choc Vending",
        sku: 52088,
        image: "/images/products/product-2.jpg",
        price: 143.68,
        qty: 5,
        discount: 0.45,
        total: 282.24,
        product_id: "PROD-6xjaaq5u",
      },
      {
        name: "Rhubarb",
        sku: 97706,
        image: "/images/products/product-12.jpg",
        price: 136.54,
        qty: 1,
        discount: 0.37,
        total: 412.96,
        product_id: "PROD-z1yxtbnf",
      },
      {
        name: "Samosa - Veg",
        sku: 31080,
        image: "/images/products/product-2.jpg",
        price: 337.43,
        qty: 6,
        discount: 0.25,
        total: 850.64,
        product_id: "PROD-9nh8ef1l",
      },
      {
        name: "Cup - Translucent 7 Oz Clear",
        sku: 50627,
        image: "/images/products/product-11.jpg",
        price: 546.09,
        qty: 8,
        discount: 0.24,
        total: 84.03,
        product_id: "PROD-vovv2kgt",
      },
      {
        name: "Wine - Cahors Ac 2000, Clos",
        sku: 74133,
        image: "/images/products/product-11.jpg",
        price: 399.34,
        qty: 4,
        discount: 0.39,
        total: 318.51,
        product_id: "PROD-4sv8tl4d",
      },
    ],
    subtotal: 750.7,
    delivery_fee: 27.72,
    tax: 20,
    total_amount_due: 220.93,
  },
  {
    order_id: "#57024",
    created_at: "1668075741000",
    customer: {
      name: "Raphael MacCallum",
      avatar_img: "/images/avatar/avatar-19.jpg",
      customer_id: "CUST-zmv23lpk",
    },
    total: 498.84,
    profit: 129.6984,
    payment_status: "paid",
    order_status: "pending",
    shipping_address: { street: "7403 Glendale Drive", line: "Room 1634" },
    products: [
      {
        name: "Strawberries - California",
        sku: 21669,
        image: "/images/products/product-6.jpg",
        price: 400.08,
        qty: 9,
        discount: 0.33,
        total: 26.21,
        product_id: "PROD-8ieotw68",
      },
      {
        name: "Wine - White, Pinot Grigio",
        sku: 97917,
        image: "/images/products/product-12.jpg",
        price: 564.07,
        qty: 3,
        discount: 0.38,
        total: 626.07,
        product_id: "PROD-802yo2lx",
      },
      {
        name: "Crab - Meat",
        sku: 37637,
        image: "/images/products/product-9.jpg",
        price: 112.58,
        qty: 1,
        discount: 0.28,
        total: 121.68,
        product_id: "PROD-t4vy8u4i",
      },
      {
        name: "Wine - Chianti Classica Docg",
        sku: 54427,
        image: "/images/products/product-3.jpg",
        price: 925.28,
        qty: 4,
        discount: 0.18,
        total: 362.73,
        product_id: "PROD-ihmqegt4",
      },
      {
        name: "Rum - Mount Gay Eclipes",
        sku: 92559,
        image: "/images/products/product-5.jpg",
        price: 618.71,
        qty: 8,
        discount: 0.46,
        total: 251.39,
        product_id: "PROD-bs0lrzxo",
      },
      {
        name: "Cheese - Shred Cheddar / Mozza",
        sku: 23959,
        image: "/images/products/product-9.jpg",
        price: 27.32,
        qty: 1,
        discount: 0.39,
        total: 922.2,
        product_id: "PROD-uw0jnxh9",
      },
      {
        name: "Mayonnaise",
        sku: 49638,
        image: "/images/products/product-5.jpg",
        price: 294.82,
        qty: 7,
        discount: 0.02,
        total: 961.94,
        product_id: "PROD-ab05rj34",
      },
      {
        name: "Wine - White, Riesling, Henry Of",
        sku: 60059,
        image: "/images/products/product-6.jpg",
        price: 671.26,
        qty: 10,
        discount: 0.2,
        total: 894.95,
        product_id: "PROD-zt48bj5i",
      },
    ],
    subtotal: 628.29,
    delivery_fee: 35.11,
    tax: 20,
    total_amount_due: 941.32,
  },
  {
    order_id: "#54441",
    created_at: "1670770488000",
    customer: {
      name: "Thea Lewens",
      avatar_img: "/images/avatar/avatar-20.jpg",
      customer_id: "CUST-r3mxasw5",
    },
    total: 277.1,
    profit: 108.069,
    payment_status: "paid",
    order_status: "cancelled",
    shipping_address: { street: "0938 Esker Pass", line: "Room 686" },
    products: [
      {
        name: "Tuna - Canned, Flaked, Light",
        sku: 52048,
        image: "/images/products/product-12.jpg",
        price: 139.17,
        qty: 7,
        discount: 0.04,
        total: 46.24,
        product_id: "PROD-0evrhyo9",
      },
      {
        name: "Soup - Campbells Chili Veg",
        sku: 57670,
        image: "/images/products/product-7.jpg",
        price: 514.2,
        qty: 4,
        discount: 0.29,
        total: 375.92,
        product_id: "PROD-6uqu7g56",
      },
      {
        name: "Wine - Rosso Toscano Igt",
        sku: 74922,
        image: "/images/products/product-10.jpg",
        price: 504.27,
        qty: 7,
        discount: 0.19,
        total: 987.67,
        product_id: "PROD-e7pdwi3e",
      },
      {
        name: "Cheese - Augre Des Champs",
        sku: 99169,
        image: "/images/products/product-11.jpg",
        price: 153.39,
        qty: 5,
        discount: 0.07,
        total: 156.49,
        product_id: "PROD-qm1a6975",
      },
      {
        name: "Mussels - Cultivated",
        sku: 93065,
        image: "/images/products/product-4.jpg",
        price: 607.92,
        qty: 8,
        discount: 0.32,
        total: 790.31,
        product_id: "PROD-sdaoldbf",
      },
      {
        name: "Trout - Rainbow, Frozen",
        sku: 4215,
        image: "/images/products/product-5.jpg",
        price: 826.68,
        qty: 5,
        discount: 0.4,
        total: 898.31,
        product_id: "PROD-f22nn31m",
      },
    ],
    subtotal: 733.95,
    delivery_fee: 34.99,
    tax: 20,
    total_amount_due: 790.97,
  },
  {
    order_id: "#51271",
    created_at: "1665915069000",
    customer: {
      name: "Cesare Hare",
      avatar_img: "/images/avatar/avatar-10.jpg",
      customer_id: "CUST-bt82nk23",
    },
    total: 567.79,
    profit: 102.2022,
    payment_status: "pending",
    order_status: "cancelled",
    shipping_address: { street: "72011 Onsgard Pass", line: "Apt 1757" },
    products: [
      {
        name: "Vector Energy Bar",
        sku: 32825,
        image: "/images/products/product-2.jpg",
        price: 715.4,
        qty: 2,
        discount: 0.59,
        total: 71.37,
        product_id: "PROD-ef3vz4d7",
      },
      {
        name: "Glycerine",
        sku: 17796,
        image: "/images/products/product-2.jpg",
        price: 334.9,
        qty: 8,
        discount: 0.47,
        total: 270.08,
        product_id: "PROD-41f2txn8",
      },
      {
        name: "Beets - Candy Cane, Organic",
        sku: 1519,
        image: "/images/products/product-4.jpg",
        price: 35.12,
        qty: 6,
        discount: 0.18,
        total: 698.9,
        product_id: "PROD-ap9e1wew",
      },
      {
        name: "Tea - Herbal I Love Lemon",
        sku: 76687,
        image: "/images/products/product-7.jpg",
        price: 460.25,
        qty: 3,
        discount: 0.3,
        total: 30.45,
        product_id: "PROD-0lo619oj",
      },
      {
        name: "Waffle Stix",
        sku: 65797,
        image: "/images/products/product-4.jpg",
        price: 894.1,
        qty: 4,
        discount: 0.33,
        total: 877.05,
        product_id: "PROD-yqgytwez",
      },
      {
        name: "Tobasco Sauce",
        sku: 94464,
        image: "/images/products/product-8.jpg",
        price: 143.5,
        qty: 8,
        discount: 0.2,
        total: 225.83,
        product_id: "PROD-37efyhqc",
      },
      {
        name: "V8 Splash Strawberry Kiwi",
        sku: 88388,
        image: "/images/products/product-6.jpg",
        price: 922.52,
        qty: 0,
        discount: 0.17,
        total: 583.68,
        product_id: "PROD-tep2ex6o",
      },
      {
        name: "Chervil - Fresh",
        sku: 21989,
        image: "/images/products/product-8.jpg",
        price: 413.47,
        qty: 5,
        discount: 0.16,
        total: 88.11,
        product_id: "PROD-c6jnsvcx",
      },
    ],
    subtotal: 774.78,
    delivery_fee: 71.83,
    tax: 20,
    total_amount_due: 139.96,
  },
  {
    order_id: "#25850",
    created_at: "1663655579000",
    customer: {
      name: "Emalee Scad",
      avatar_img: "/images/avatar/avatar-12.jpg",
      customer_id: "CUST-efc8qoma",
    },
    total: 592.28,
    profit: 124.3788,
    payment_status: "pending",
    order_status: "pending",
    shipping_address: { street: "1023 Gulseth Trail", line: "Suite 51" },
    products: [
      {
        name: "Coffee - Irish Cream",
        sku: 97419,
        image: "/images/products/product-11.jpg",
        price: 640.12,
        qty: 5,
        discount: 0.23,
        total: 429.73,
        product_id: "PROD-56zlag9i",
      },
      {
        name: "Cream - 10%",
        sku: 53380,
        image: "/images/products/product-6.jpg",
        price: 679.68,
        qty: 5,
        discount: 0.6,
        total: 152.07,
        product_id: "PROD-7vloq1cd",
      },
      {
        name: "Beer - Heinekin",
        sku: 12657,
        image: "/images/products/product-10.jpg",
        price: 519.41,
        qty: 1,
        discount: 0.37,
        total: 778.32,
        product_id: "PROD-3zukznad",
      },
    ],
    subtotal: 376.81,
    delivery_fee: 54.01,
    tax: 20,
    total_amount_due: 539.73,
  },
  {
    order_id: "#35676",
    created_at: "1657947061000",
    customer: {
      name: "Peggy Lakey",
      avatar_img: "/images/avatar/avatar-11.jpg",
      customer_id: "CUST-zvwth5pn",
    },
    total: 832.39,
    profit: 474.4623,
    payment_status: "failed",
    order_status: "completed",
    shipping_address: { street: "9507 Westend Junction", line: "Room 1781" },
    products: [
      {
        name: "Bread - Bistro White",
        sku: 64318,
        image: "/images/products/product-2.jpg",
        price: 45.83,
        qty: 4,
        discount: 0.38,
        total: 385.08,
        product_id: "PROD-job8gpwq",
      },
      {
        name: "Gherkin - Sour",
        sku: 57083,
        image: "/images/products/product-5.jpg",
        price: 408.67,
        qty: 4,
        discount: 0.38,
        total: 285.57,
        product_id: "PROD-bt5eco96",
      },
      {
        name: "Lemon Balm - Fresh",
        sku: 23288,
        image: "/images/products/product-6.jpg",
        price: 765.4,
        qty: 9,
        discount: 0.15,
        total: 596.2,
        product_id: "PROD-nod7n9by",
      },
      {
        name: "Muffin - Mix - Bran And Maple 15l",
        sku: 98339,
        image: "/images/products/product-1.jpg",
        price: 296.34,
        qty: 9,
        discount: 0.21,
        total: 400.16,
        product_id: "PROD-hywv2118",
      },
      {
        name: "Calvados - Boulard",
        sku: 5155,
        image: "/images/products/product-8.jpg",
        price: 833.9,
        qty: 3,
        discount: 0.5,
        total: 557.02,
        product_id: "PROD-hj4aoz7c",
      },
      {
        name: "Coke - Diet, 355 Ml",
        sku: 18418,
        image: "/images/products/product-5.jpg",
        price: 941.76,
        qty: 4,
        discount: 0.36,
        total: 336.01,
        product_id: "PROD-ixmo85n0",
      },
      {
        name: "Sugar - Invert",
        sku: 58386,
        image: "/images/products/product-9.jpg",
        price: 629.67,
        qty: 1,
        discount: 0.27,
        total: 177.56,
        product_id: "PROD-bzmd6qjf",
      },
      {
        name: "Pork - Hock And Feet Attached",
        sku: 37791,
        image: "/images/products/product-7.jpg",
        price: 617.71,
        qty: 9,
        discount: 0.15,
        total: 345.08,
        product_id: "PROD-sc652rlt",
      },
    ],
    subtotal: 95.75,
    delivery_fee: 23.68,
    tax: 20,
    total_amount_due: 612.38,
  },
  {
    order_id: "#98026",
    created_at: "1679059050000",
    customer: {
      name: "Myriam Rawlcliffe",
      avatar_img: "/images/avatar/avatar-3.jpg",
      customer_id: "CUST-7x5l6e3r",
    },
    total: 163.56,
    profit: 35.9832,
    payment_status: "failed",
    order_status: "cancelled",
    shipping_address: { street: "3641 Lerdahl Park", line: "Suite 9" },
    products: [
      {
        name: "Tendrils - Baby Pea, Organic",
        sku: 85862,
        image: "/images/products/product-5.jpg",
        price: 619.67,
        qty: 10,
        discount: 0.17,
        total: 285.0,
        product_id: "PROD-2snaikzi",
      },
      {
        name: "Lid - 0090 Clear",
        sku: 20022,
        image: "/images/products/product-9.jpg",
        price: 270.06,
        qty: 8,
        discount: 0.3,
        total: 631.29,
        product_id: "PROD-enmubp2n",
      },
      {
        name: "Bread - Dark Rye, Loaf",
        sku: 61356,
        image: "/images/products/product-8.jpg",
        price: 570.36,
        qty: 4,
        discount: 0.54,
        total: 868.08,
        product_id: "PROD-ghbalrxc",
      },
      {
        name: "Melon - Watermelon Yellow",
        sku: 36284,
        image: "/images/products/product-7.jpg",
        price: 365.61,
        qty: 1,
        discount: 0.4,
        total: 258.96,
        product_id: "PROD-v8yofgt1",
      },
      {
        name: "Munchies Honey Sweet Trail Mix",
        sku: 62555,
        image: "/images/products/product-10.jpg",
        price: 151.77,
        qty: 8,
        discount: 0.16,
        total: 24.9,
        product_id: "PROD-zm6n1f9t",
      },
      {
        name: "Wine - Prem Select Charddonany",
        sku: 37826,
        image: "/images/products/product-6.jpg",
        price: 925.88,
        qty: 5,
        discount: 0.38,
        total: 742.88,
        product_id: "PROD-ynnk74cl",
      },
      {
        name: "Coffee Swiss Choc Almond",
        sku: 33478,
        image: "/images/products/product-4.jpg",
        price: 787.28,
        qty: 8,
        discount: 0.54,
        total: 433.27,
        product_id: "PROD-bn7dy8ag",
      },
      {
        name: "Cocoa Powder - Natural",
        sku: 68608,
        image: "/images/products/product-10.jpg",
        price: 974.06,
        qty: 4,
        discount: 0.49,
        total: 391.56,
        product_id: "PROD-snrwp2vv",
      },
      {
        name: "Sauce - Mint",
        sku: 97155,
        image: "/images/products/product-7.jpg",
        price: 837.59,
        qty: 10,
        discount: 0.01,
        total: 914.27,
        product_id: "PROD-6esg8ack",
      },
    ],
    subtotal: 919.15,
    delivery_fee: 87.72,
    tax: 20,
    total_amount_due: 215.6,
  },
  {
    order_id: "#91638",
    created_at: "1682516933000",
    customer: {
      name: "Reeta Houlton",
      avatar_img: "/images/avatar/avatar-12.jpg",
      customer_id: "CUST-fy154iib",
    },
    total: 67.64,
    profit: 35.8492,
    payment_status: "pending",
    order_status: "cancelled",
    shipping_address: {
      street: "89092 Pepper Wood Street",
      line: "PO Box 35124",
    },
    products: [
      {
        name: "Wine - Lamancha Do Crianza",
        sku: 16010,
        image: "/images/products/product-8.jpg",
        price: 35.09,
        qty: 5,
        discount: 0.43,
        total: 635.28,
        product_id: "PROD-dv9cuppj",
      },
      {
        name: "Veal - Eye Of Round",
        sku: 53580,
        image: "/images/products/product-11.jpg",
        price: 80.87,
        qty: 5,
        discount: 0.02,
        total: 618.58,
        product_id: "PROD-y8a9rtq2",
      },
      {
        name: "Oil - Olive",
        sku: 36807,
        image: "/images/products/product-10.jpg",
        price: 569.89,
        qty: 0,
        discount: 0.17,
        total: 425.8,
        product_id: "PROD-21dtorcr",
      },
      {
        name: "Beer - Heinekin",
        sku: 4581,
        image: "/images/products/product-10.jpg",
        price: 707.49,
        qty: 8,
        discount: 0.11,
        total: 538.18,
        product_id: "PROD-58jyc18s",
      },
      {
        name: "Red Snapper - Fresh, Whole",
        sku: 64955,
        image: "/images/products/product-6.jpg",
        price: 205.73,
        qty: 5,
        discount: 0.26,
        total: 303.43,
        product_id: "PROD-3nre45jq",
      },
      {
        name: "Pepper - Black, Ground",
        sku: 63640,
        image: "/images/products/product-3.jpg",
        price: 637.33,
        qty: 1,
        discount: 0.46,
        total: 376.47,
        product_id: "PROD-b3k4mzdx",
      },
      {
        name: "Vodka - Lemon, Absolut",
        sku: 25085,
        image: "/images/products/product-3.jpg",
        price: 551.52,
        qty: 3,
        discount: 0.19,
        total: 702.48,
        product_id: "PROD-15796nmz",
      },
      {
        name: "Wine - White, Antinore Orvieto",
        sku: 99136,
        image: "/images/products/product-11.jpg",
        price: 662.36,
        qty: 0,
        discount: 0.23,
        total: 944.75,
        product_id: "PROD-k7jasdnn",
      },
    ],
    subtotal: 986.54,
    delivery_fee: 4.42,
    tax: 20,
    total_amount_due: 447.3,
  },
  {
    order_id: "#94167",
    created_at: "1664892942000",
    customer: {
      name: "Vallie Hasney",
      avatar_img: "/images/avatar/avatar-12.jpg",
      customer_id: "CUST-0deet5gd",
    },
    total: 334.3,
    profit: 147.092,
    payment_status: "pending",
    order_status: "processing",
    shipping_address: { street: "6 Clemons Trail", line: "Room 672" },
    products: [
      {
        name: "Cabbage - Green",
        sku: 52474,
        image: "/images/products/product-1.jpg",
        price: 539.87,
        qty: 5,
        discount: 0.39,
        total: 634.98,
        product_id: "PROD-gvnj4c68",
      },
      {
        name: "Wine - Acient Coast Caberne",
        sku: 21954,
        image: "/images/products/product-3.jpg",
        price: 937.36,
        qty: 0,
        discount: 0.4,
        total: 33.66,
        product_id: "PROD-rewt9089",
      },
      {
        name: "Bar Energy Chocchip",
        sku: 85140,
        image: "/images/products/product-4.jpg",
        price: 912.92,
        qty: 0,
        discount: 0.52,
        total: 713.33,
        product_id: "PROD-hykynlhi",
      },
      {
        name: "Lamb - Shoulder",
        sku: 76146,
        image: "/images/products/product-1.jpg",
        price: 844.8,
        qty: 0,
        discount: 0.06,
        total: 642.31,
        product_id: "PROD-jj60pedi",
      },
      {
        name: "Pasta - Agnolotti - Butternut",
        sku: 68345,
        image: "/images/products/product-12.jpg",
        price: 541.25,
        qty: 0,
        discount: 0.41,
        total: 972.44,
        product_id: "PROD-dettqha6",
      },
      {
        name: "Wiberg Super Cure",
        sku: 35092,
        image: "/images/products/product-6.jpg",
        price: 427.14,
        qty: 5,
        discount: 0.0,
        total: 603.49,
        product_id: "PROD-k7sd4j9e",
      },
      {
        name: "Wine - Beringer Founders Estate",
        sku: 9148,
        image: "/images/products/product-1.jpg",
        price: 298.69,
        qty: 9,
        discount: 0.17,
        total: 838.54,
        product_id: "PROD-8cz1c69t",
      },
    ],
    subtotal: 965.02,
    delivery_fee: 83.37,
    tax: 20,
    total_amount_due: 574.35,
  },
  {
    order_id: "#89547",
    created_at: "1665534033000",
    customer: {
      name: "Joelle Sweetsur",
      avatar_img: "/images/avatar/avatar-11.jpg",
      customer_id: "CUST-x21ievma",
    },
    total: 396.97,
    profit: 87.3334,
    payment_status: "paid",
    order_status: "completed",
    shipping_address: { street: "4904 Iowa Parkway", line: "13th Floor" },
    products: [
      {
        name: "Parsley Italian - Fresh",
        sku: 1308,
        image: "/images/products/product-4.jpg",
        price: 179.43,
        qty: 0,
        discount: 0.07,
        total: 687.84,
        product_id: "PROD-s0qmnapn",
      },
      {
        name: "Sambuca - Opal Nera",
        sku: 18232,
        image: "/images/products/product-11.jpg",
        price: 84.63,
        qty: 9,
        discount: 0.14,
        total: 195.26,
        product_id: "PROD-21eo760b",
      },
      {
        name: "Beans - Turtle, Black, Dry",
        sku: 80557,
        image: "/images/products/product-7.jpg",
        price: 134.21,
        qty: 10,
        discount: 0.14,
        total: 305.43,
        product_id: "PROD-bw17uy0a",
      },
      {
        name: "Anchovy Paste - 56 G Tube",
        sku: 6160,
        image: "/images/products/product-11.jpg",
        price: 757.15,
        qty: 10,
        discount: 0.07,
        total: 685.2,
        product_id: "PROD-nhe3k6un",
      },
      {
        name: "Beer - Fruli",
        sku: 64715,
        image: "/images/products/product-3.jpg",
        price: 85.58,
        qty: 9,
        discount: 0.52,
        total: 414.71,
        product_id: "PROD-247nkl6a",
      },
      {
        name: "Anisette - Mcguiness",
        sku: 34714,
        image: "/images/products/product-12.jpg",
        price: 947.09,
        qty: 5,
        discount: 0.3,
        total: 227.95,
        product_id: "PROD-0bvjztzv",
      },
      {
        name: "Extract Vanilla Pure",
        sku: 62312,
        image: "/images/products/product-12.jpg",
        price: 552.96,
        qty: 6,
        discount: 0.49,
        total: 623.29,
        product_id: "PROD-4txkgvvm",
      },
      {
        name: "Beans - Fava, Canned",
        sku: 60331,
        image: "/images/products/product-10.jpg",
        price: 301.06,
        qty: 10,
        discount: 0.11,
        total: 669.62,
        product_id: "PROD-f1spcqjc",
      },
    ],
    subtotal: 891.19,
    delivery_fee: 84.54,
    tax: 20,
    total_amount_due: 307.54,
  },
  {
    order_id: "#14957",
    created_at: "1669970350000",
    customer: {
      name: "Rockwell Vedstra",
      avatar_img: "/images/avatar/avatar-11.jpg",
      customer_id: "CUST-yxvt8yfy",
    },
    total: 988.9,
    profit: 276.892,
    payment_status: "paid",
    order_status: "pending",
    shipping_address: { street: "784 Upham Pass", line: "Room 1603" },
    products: [
      {
        name: "Pasta - Lasagne, Fresh",
        sku: 68281,
        image: "/images/products/product-8.jpg",
        price: 124.65,
        qty: 9,
        discount: 0.55,
        total: 61.88,
        product_id: "PROD-3lbv0chz",
      },
      {
        name: "Squid - Tubes / Tenticles 10/20",
        sku: 43483,
        image: "/images/products/product-11.jpg",
        price: 811.06,
        qty: 3,
        discount: 0.29,
        total: 719.19,
        product_id: "PROD-b74gxlrr",
      },
    ],
    subtotal: 333.6,
    delivery_fee: 73.56,
    tax: 20,
    total_amount_due: 310.95,
  },
  {
    order_id: "#31090",
    created_at: "1656693101000",
    customer: {
      name: "Drona Le Barre",
      avatar_img: null,
      customer_id: "CUST-upriqhmd",
    },
    total: 48.46,
    profit: 17.9302,
    payment_status: "paid",
    order_status: "processing",
    shipping_address: { street: "5 Cascade Pass", line: "15th Floor" },
    products: [
      {
        name: "Beans - Green",
        sku: 60931,
        image: "/images/products/product-10.jpg",
        price: 136.8,
        qty: 8,
        discount: 0.17,
        total: 811.34,
        product_id: "PROD-dnb1weyx",
      },
      {
        name: "Wasabi Powder",
        sku: 42854,
        image: "/images/products/product-4.jpg",
        price: 985.05,
        qty: 10,
        discount: 0.16,
        total: 400.05,
        product_id: "PROD-m98fwawa",
      },
    ],
    subtotal: 930.49,
    delivery_fee: 71.46,
    tax: 20,
    total_amount_due: 392.41,
  },
];
